### ISSUE TITLE
support for quantization and qlora models?

### ISSUE THREAD

**Issue by thistleknot** [vllm-project/vllm#906] opened 2023-08-29 13:55 UTC
would love to use this with quantization and adapters

**Comment by Gregory-Ledray** [comment] 2023-08-30 16:40
I am not a maintainer.

This is a duplicate of https://github.com/vllm-project/vllm/issues/744

**Comment by LopezGG** [comment] 2023-09-04 10:09
I am using vllm with qlora. I merge the adapters with 
```
model_for_merge = AutoModelForCausalLM.from_pretrained(
        base_model_path_or_name,
        torch_dtype=torch.float16,
    )
    full_model = PeftModel.from_pretrained(model_for_merge,
                                          model_id=script_args.adapter_dir,
                                        )
    full_model = full_model.base_model.merge_and_unload()  
    full_model.save_pretrained(script_args.full_model_dir)
    tokenizer.save_pretrained(script_args.full_model_dir)
```
and point vllm to this dir. Given that the A & B matrices are added to original weight matrices, there is no change in dimension or architecture.  So, vllm can consume it. I would like a way to pass the model directly after load without saving it though

**Comment by hmellor** [comment] 2024-03-08 11:24
Closing in favour of #3225 because quantization and LoRA are both supported. We just need QLoRA support.

**Closed by hmellor** 2024-03-08 11:24 UTC
