### ISSUE TITLE
Greedy decoding generates different outputs

### ISSUE THREAD

**Issue by FocusLiwen** [vllm-project/vllm#1202] opened 2023-09-27 20:46 UTC
I have tried the same prompt to run 100 times with temp=0, top_p=1, I did not get the same results for 100 times. But there are a few dominated outputs there. My understanding is that with the setup, greedy decoding should generate the same outputs with the same prompt. But this is not what I observed.

**Comment by viktor-ferenczi** [comment] 2023-09-28 06:24
Please provide the OS, CUDA version, CPU, CPU RAM, GPU(s), GPU VRAM sizes, command line you started the vLLM with, model used, prompt(s) and the full vLLM log output for diagnosis.

Possible duplicate of #608

**Comment by hmellor** [comment] 2024-03-13 11:09
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Closed by hmellor** 2024-03-13 11:09 UTC
