### ISSUE TITLE
[Bug]: --engine-use-ray is broken.

### ISSUE THREAD

**Issue by rkooo567** [vllm-project/vllm#4100] opened 2024-04-15 22:44 UTC
### Your current environment

N/A (happens in all env)

### 🐛 Describe the bug

```
python -m vllm.entrypoints.openai.api_server --model "facebook/opt-125m" --dtype auto --api-key token-abc123 --engine-use-ray
```

When I start an openai server with engine-use-ray, I found it crashes with the following error

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ray/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ray/default/vllm/vllm/entrypoints/openai/api_server.py", line 157, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/home/ray/default/vllm/vllm/engine/async_llm_engine.py", line 347, in from_engine_args
    engine = cls(
  File "/home/ray/default/vllm/vllm/engine/async_llm_engine.py", line 311, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/ray/default/vllm/vllm/engine/async_llm_engine.py", line 413, in _init_engine
    cache_config = args[1]
IndexError: tuple index out of range
```

**Comment by jdinalt** [comment] 2024-04-16 01:21
I suspect an "off-by-one" index error in the worker.

I am seeing what looks like a related failure when passing "--tensor-parallel-size 4"

I added some instrumentation to the failure point:

vllm/worker/worker.py
```
...
309 def _check_if_gpu_supports_dtype(torch_dtype: torch.dtype):                                                             
310     # Check if the GPU supports the dtype.                                                                              
311     if torch_dtype == torch.bfloat16:                                                                                   
312         print("Current Device:")                                                                                        
313         print(torch.cuda.current_device(), "of", torch.cuda.device_count())                                             
314         compute_capability = torch.cuda.get_device_capability()
...
```

```
(RayWorkerVllm pid=2098) INFO 04-16 01:10:45 selector.py:28] Using FlashAttention backend.
Current Device:
0 of 4
(RayWorkerVllm pid=2098) Current Device:
(RayWorkerVllm pid=2098) 1 of 1
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50] Error executing method init_device. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50] Traceback (most recent call last):
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]   File "/home/dinalt/ai_assets/code/vllm/vllm/engine/ray_utils.py", line 43, in execute_method
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]     return executor(*args, **kwargs)
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]   File "/home/dinalt/ai_assets/code/vllm/vllm/worker/worker.py", line 99, in init_device
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]     _check_if_gpu_supports_dtype(self.model_config.dtype)
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]   File "/home/dinalt/ai_assets/code/vllm/vllm/worker/worker.py", line 314, in _check_if_gpu_supports_dtype
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]     compute_capability = torch.cuda.get_device_capability()
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]   File "/home/dinalt/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 439, in get_device_capability
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]     prop = get_device_properties(device)
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]   File "/home/dinalt/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 456, in get_device_properties
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50]     raise AssertionError("Invalid device id")
(RayWorkerVllm pid=2098) ERROR 04-16 01:10:45 ray_utils.py:50] AssertionError: Invalid device id
```

You can see that the device index assigned to the worker is "1 of 1," where the only valid index is '0' for a single assigned GPU.

I'll see if I can root-cause it...

**Comment by jdinalt** [comment] 2024-04-16 02:04
I have located the commit which caused the breakage via binary search. It's large enough that it may take a bit of time to parse the details of the change and identify where things went wrong.

https://github.com/vllm-project/vllm/commit/09473ee41c0a22c4d18936ea7eb2328071c19308

If you roll back to the commit immediately preceding the above:
```
git reset --hard d4ec9ffb9574988132d927fd1615180522877262
```

...Ray works again.

And moving forward to the identified commit breaks it.

**Comment by jdinalt** [comment] 2024-04-16 03:29
I was able to trace the issue to the modification of "ray_utils.py"

The bug does not appear to be in the changes made to this file but a side effect of importing the "Worker" module.

The following diff is sufficient to eliminate the problem:
```
diff --git a/vllm/engine/ray_utils.py b/vllm/engine/ray_utils.py
index 04d4ed8..175fa6f 100644
--- a/vllm/engine/ray_utils.py
+++ b/vllm/engine/ray_utils.py
@@ -4,7 +4,7 @@ from typing import Callable, List, Optional, Tuple
 from vllm.config import ParallelConfig
 from vllm.logger import init_logger
 from vllm.utils import get_ip, is_hip, set_cuda_visible_devices
-from vllm.worker.worker import Worker
+#from vllm.worker.worker import Worker
 
 logger = init_logger(__name__)
 
@@ -19,18 +19,18 @@ try:
             if init_cached_hf_modules:
                 from transformers.dynamic_module_utils import init_hf_modules
                 init_hf_modules()
-            self._worker: Optional[Worker] = None
+            self._worker = None
             # Since the compiled DAG runs a main execution
             # in a different thread that calls cuda.set_device.
             # The flag indicates is set_device is called on
             # that thread.
             self.compiled_dag_cuda_device_set = False
 
-        def init_worker(self, worker_init_fn: Callable[[], Worker]):
+        def init_worker(self, worker_init_fn):
             self._worker = worker_init_fn()
 
         @property
-        def worker(self) -> Worker:
+        def worker(self):
             assert self._worker is not None
             return self._worker
```

Of the changes to this file, the problem persists until the line importing "Worker" is removed. This implicates a fragile initialization order dependency. I did not see anything obviously wrong in "worker.py," so it's likely caused by a direct or indirect import of that module. My money would be on one of the "distributed" related imports.

Anyhow, the above patch should be sufficient to at least make the library usable again with multiple GPUs. The initialization order dependency has yet to be identified.

**Comment by rkooo567** [comment] 2024-04-16 03:46
@jdinalt thanks for the investigation! do you plan to create a PR? I think we should also make sure to have unit tests for this code path

**Comment by jdinalt** [comment] 2024-04-16 03:48
With respect to the original test case:
```
python -m vllm.entrypoints.openai.api_server --model "facebook/opt-125m" --dtype auto --api-key token-abc123 --engine-use-ray
```
I can reproduce the bug with and without my change, but it is not present if I explicitly set the tensor parallel size:
```
python -m vllm.entrypoints.openai.api_server --tensor-parallel-size 4 --model "facebook/opt-125m" --dtype auto --api-key token-abc123 --engine-use-ray
```
My suspicion is that it relates to having 6 GPUs on my system, which is not a power-of-two.

It still crashes and burns without my patch above, but with both the patch and specifying the size, it works fine.

**Comment by jdinalt** [comment] 2024-04-16 03:50
@rkooo567 Sure. I'll create a PR. I would really like to know what the real issue is, as that has not been solved, but this is at least good enough to make it usable again.

And if you would like another hand with this project, I'm happy to help.

**Comment by rkooo567** [comment] 2024-04-16 04:02
actually I may have identified the root cause... making a PR now

**Comment by rkooo567** [comment] 2024-04-16 04:07
https://github.com/vllm-project/vllm/pull/4105/files lmk if this makes sense @jdinalt

**Comment by jdinalt** [comment] 2024-04-16 05:09
Re: Pull 4105

The test looks like it should do what is desired. At present, there appears to be something broken with respect to having to manually specify "--tensor-parallel-size."

I suspect that this is a separate bug related to automatically determining the tensor-parallel size when not explicitly specified. It does not appear to be related to my six GPU setup, as the following command still fails:

```
CUDA_VISIBLE_DEVICES="0,1,2,3" python -m vllm.entrypoints.openai.api_server --model "facebook/opt-125m" --dtype auto --api-key token-abc123 --engine-use-ray
```

Before the unit test is checked in, the root cause of the above needs to be determined and fixed.

I'll dig in a little deeper, as it is obviously not setting that parameter automatically to the number of GPUs.

**Comment by jdinalt** [comment] 2024-04-16 05:17
Sorry. I somehow missed the second half of your PR.

Just came to the same conclusion, so I think your change will work.

**Closed** 2024-04-16 05:24 UTC
Labels: bug

**Comment by jdinalt** [comment] 2024-04-16 05:42
I ran my test with Pull 4105, both on its own and with my PR.

```
python -m vllm.entrypoints.openai.api_server --model "facebook/opt-125m" --dtype auto --api-key token-abc123 --engine-use-ray
```
PR4105: Pass
PR4105 + PR4106: Pass

I noted that the tensor-parallel level was "1" for this test, with only a single GPU being utilized.

```
python -m vllm.entrypoints.openai.api_server --tensor-parallel-size 4 --model "facebook/opt-125m" --dtype auto --api-key token-abc123 --engine-use-ray
```
PR4105: Fail
PR4105 + PR4106: Pass

When the tensor-parallel value is greater than one, the test fails with only PR4105, hitting the bug I came across.

You may want to add an explicit parallel configuration to the tests to catch this type of failure.

**Comment by rkooo567** [comment] 2024-04-16 13:52
ah interesting higher tp size breaks the test... let me try that out tmrw. Your PR is supposed fix the issue? (it is surprising given your PR only changes the typing annotation...?)
