### ISSUE TITLE
Support Dynamic SplitFuse 

### ISSUE THREAD

**Issue by dongxiaolong** [vllm-project/vllm#1569] opened 2023-11-06 02:09 UTC
https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fastgen#background
In their experiment, DeepSpeed-FastGen outperforms vLLM in both throughput and latency, providing equivalent latency with greater throughput or more responsive latency and the same throughput. 
I think the main reason is the dynamic splitFuse method, can vllm support it ?

**Comment by WoosukKwon** [comment] 2023-11-07 01:40
Hi @dongxiaolong, thanks for the proposal. However, it seems this issue is a duplicate of #1562. I will close it to reduce redundancy.

**Closed by WoosukKwon** 2023-11-07 01:40 UTC
