### ISSUE TITLE
Mistral model architecture is not supported

### ISSUE THREAD

**Issue by Hypothesis-Z** [vllm-project/vllm#2749] opened 2024-02-05 03:15 UTC
The Mistral model is [🤗Salesforce/SFR-Embedding-Mistral](https://huggingface.co/Salesforce/SFR-Embedding-Mistral).

```shell
INFO 02-05 03:05:04 llm_engine.py:72] Initializing an LLM engine with config: model='SFR-Embedding-Mistral', tokenizer='SFR-Embedding-Mistral', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, seed=0)
Traceback (most recent call last):
  File "/app/embedding.py", line 33, in <module>
    model = LLM('SFR-Embedding-Mistral')
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 109, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 356, in from_engine_args
    engine = cls(*engine_configs,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 111, in __init__
    self._init_workers()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 152, in _init_workers
    self._run_workers("load_model")
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 983, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 92, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 75, in load_model
    self.model = get_model(self.model_config, self.lora_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 42, in get_model
    model_class = _get_model_architecture(model_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 35, in _get_model_architecture
    raise ValueError(
ValueError: Model architectures ['MistralModel'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'YiForCausalLM']
```

**Comment by dekavox** [comment] 2024-02-05 06:42
Hi @Hypothesis-Z,

it seems that the model you're trying to load is an "embeddings"-model rather than a "text-gerenation"-model.
Hence the model architecture is a completely different one (output is a [1, 4096] embeddings-vector).

I don't think vLLM will support embeddings-models.

Cheers

**Comment by hmellor** [comment] 2024-02-07 13:54
@dekavox is right that vLLM doesn't currently support embedding models.

However, adding support for embedding models is on vLLM's Q1 roadmap #2681

**Comment by hmellor** [comment] 2024-03-06 09:19
Closing this as a duplicate of #742

**Closed by hmellor** 2024-03-06 09:19 UTC
Labels: duplicate
