### ISSUE TITLE
Will we update to pytorch v2.2.0 ?

### ISSUE THREAD

**Issue by jony0113** [vllm-project/vllm#2738] opened 2024-02-04 03:48 UTC
pytorch v2.2.0 has already release, will we update the next version? the version v2.1.2 has a bug which will cause oom while the newest version has already fixed. https://github.com/pytorch/pytorch/issues/106294

**Comment by janelu9** [comment] 2024-02-04 05:48
Not supported yet, I tied to built it, but failed.

**Comment by hmellor** [comment] 2024-03-15 20:31
Closing as a duplicate of #2722

**Closed by hmellor** 2024-03-15 20:31 UTC
