### ISSUE TITLE
When I set tensor_parallel_size to 2, why is the inference so much slower than it is for a single card

### ISSUE THREAD

**Issue by Zhang-star-master** [vllm-project/vllm#732] opened 2023-08-11 02:01 UTC
When I set tensor_parallel_size to 2, why is the inference so much slower than it is for a single card

**Comment by Imagium719** [comment] 2023-08-11 05:37
NVLink is all you need.

**Comment by nutmilk10** [comment] 2023-08-14 23:19
> NVLink is all you need.

Can you show an example of how NVLINK would be incorporated? Thanks

**Comment by hmellor** [comment] 2024-03-08 11:13
Closing as duplicate of #689

**Closed by hmellor** 2024-03-08 11:13 UTC
Labels: duplicate
