### ISSUE TITLE
[Bug]: Seed issue with Pipeline Parallel

### ISSUE THREAD

**Issue by andoorve** [vllm-project/vllm#6449] opened 2024-07-15 18:35 UTC
### Your current environment

v0.5.1

### 🐛 Describe the bug

OpenAI API specifies that you can provide a seed: https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed

This allows reproducibility for example with non-zero temperature parameter.

Currently, any state information is stored/advanced on the driver process only. We need to extend this to the worker actually doing the sampling.

**Comment by binxuan** [comment] 2024-07-16 23:35
+ 1, got ```openai.InternalServerError: Internal Server Error``` when I specified seed in the completion request

**Comment by andoorve** [comment] 2024-07-17 02:39
@binxuan do you have any other debug information? That shouldn't be expected

**Comment by binxuan** [comment] 2024-07-18 02:46
Below is my error trace, not sure if this is the root cause.
 
> Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 919, in ray._raylet.prepare_args_internal
  File "/home/binxuan/.conda/envs/vllm_dist/lib/python3.10/site-packages/ray/_private/serialization.py", line 519, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/binxuan/.conda/envs/vllm_dist/lib/python3.10/site-packages/ray/_private/serialization.py", line 497, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "/home/binxuan/.conda/envs/vllm_dist/lib/python3.10/site-packages/ray/_private/serialization.py", line 444, in _serialize_to_pickle5
    raise e
  File "/home/binxuan/.conda/envs/vllm_dist/lib/python3.10/site-packages/ray/_private/serialization.py", line 439, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/home/binxuan/.conda/envs/vllm_dist/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/home/binxuan/.conda/envs/vllm_dist/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
TypeError: cannot pickle 'torch._C.Generator' object

**Comment by njhill** [comment] 2024-07-18 03:44
@andoorve yes this is the known issue, I should hopefully have time to fix it tomorrow.

**Comment by sekh77** [comment] 2024-07-21 13:51
Hi @njhill - Hope you have had some chance to fix this issue. Is it available now in the latest version (0.5.2)?

**Comment by njhill** [comment] 2024-07-22 16:24
@sekh77 it's not in 0.5.2. I am working on it right now and it should be ready today.

**Comment by sekh77** [comment] 2024-07-22 18:10
Ok, thanks. Will this also be available for people who are on 0.5.1?

**Comment by njhill** [comment] 2024-07-22 18:43
@sekh77 yes, it will be available to everyone! You'll just have to upgrade to the latest version (hopefully will be in a new release in the next day or two).

**Closed** 2024-07-30 17:40 UTC
Labels: bug
