### ISSUE TITLE
4 GPUs cluster (g5.12xlarge) is doing batch processing faster than 8 GPUs cluster (g5.48xlarge)

### ISSUE THREAD

**Issue by orellavie1212** [vllm-project/vllm#804] opened 2023-08-20 09:42 UTC
Hey,
I am using vllm==0.1.3 with ray >= 2.5.1 on aws sagemaker, with cuda 11.8 and llama2-13b-chat-hf.
When I am using the batch processing function (model.generate , with 3/6/15/30/45/60/105/120 texts as python list, all texts are the same one, only different number of them), the 4 gpus cluster (4 x a10g, ml.g5.12xlarge) is faster in all cases against the 8 gpus cluster (8 x a10g, ml.g5.48xlarge). I wonder maybe the tensor parallel is not working well with more than 4 gpus, or the cuda drivers not utilising them as it should be.
The temp params I am using are:
    "temperature": 0.1,
    "top_p": 0.75,
    "top_k": 40,
    "max_tokens": 256,
    "frequency_penalty": 1.07,
    "use_beam_search": False,
    "stop": ["<|endoftext|>",'[INST]', '</s>'] 
    
   for example, for 105 texts, the 4gpus cluster doing it in 47secs, and the the 8gpus cluster doing it in 59.2 secs. Also, for 60 texts the 4gpus cluster doing it in 27secs, and the the 8gpus cluster doing it in 37.3 secs.
I can provide another examples if needed.
Thanks!

**Comment by naed90** [comment] 2023-08-20 15:20
hey, shoot me an email, let's see if I can help:
dean.leitersdorf@gmail.com

**Comment by mmaaz60** [comment] 2023-08-21 02:14
Hi @orellavie1212 , @naed90,

Please keep us updated on the development on this issue. Thanks

**Comment by yeeeqichen** [comment] 2023-08-22 08:10
@mmaaz60 @orellavie1212 @naed90 
Actually, when using TP, there is an extra cost produced by the communication between different GPUs(Because the different gpus aren't working indepently, instead they need to synchronise).

So maybe the problem you're running into is reasonable, because when the gpus grows from 4 -> 8, the cost of communation also doubles(I guess). With more gpus, the single inference operation might takes more time, but it could efficiently handling multi-requests.

**Comment by orel1212** [comment] 2023-08-22 10:20
@yeeeqichen I talked with @naed90 about that case (throughput via mem bandwith vs  comms. between gpus), it requires profiling I guess and hard to say why.
Tried with TS of 2 and got results not far from 4 ( more faster than half speed of 4)...

**Comment by raihan0824** [comment] 2023-09-19 11:08
I’m experiencing the same issue, I think its weird because I thought the throughput will be linear if I double the gpu cluster. Can anybody explain this clearly? Will be super helpful

**Comment by hmellor** [comment] 2024-03-08 11:31
Closing as duplicate of #689

**Closed by hmellor** 2024-03-08 11:31 UTC
Labels: duplicate
