### ISSUE TITLE
T5 like encoder-decoder model support

### ISSUE THREAD

**Issue by XiangmingWang** [vllm-project/vllm#668] opened 2023-08-03 13:03 UTC
vllm is a great open source project and we are looking forward to running the T5 model with vllm.I know there is a plan for T5 in the roadmap, but I still want to know, is there an approximate time for this? Or can there be a specific encoder-decoder  code structure, and then everyone will work together to contribute

**Comment by shermansiu** [comment] 2023-08-16 02:07
Yes. See #187. It's also on the dev roadmap (#244).

**Comment by hmellor** [comment] 2024-03-06 08:59
Closing as duplicate of #187

**Closed by hmellor** 2024-03-06 08:59 UTC
Labels: duplicate, feature request
