### ISSUE TITLE
The API gets stuck (processing concurrent requests)

### ISSUE THREAD

**Issue by jpeig** [vllm-project/vllm#1762] opened 2023-11-23 18:07 UTC
Sometimes the API gets stuck after spamming it with concurrent requests.
It proceeds processing the requests after waiting for +/- 1 minute.

I'm using the OpenAI API and with streaming.

In spite of the API having received many requests this is the latest update the terminal gives me:

`INFO 11-23 19:12:45 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%
`

As you can see, it records just 1 request and 0 pending.

Might or might not be related to:

https://github.com/vllm-project/vllm/issues/1712
https://github.com/vllm-project/vllm/issues/1707

**Comment by simon-mo** [comment] 2023-12-01 08:53
I'm closing this as a duplicate of #1707. Please refer to that issue for deeper explanation but the TL;DR is AWQ is not optimized. It still works for low throughput use case, delivering lower latency and memory savings.

You should also see this warning in the output, what you are observing is the effect of this:
```
WARNING 12-01 08:25:34 config.py:140] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
```

**Closed by simon-mo** 2023-12-01 08:53 UTC
