### ISSUE TITLE
Can it support macos ?  M2 chip.

### ISSUE THREAD

**Issue by znsoftm** [vllm-project/vllm#1921] opened 2023-12-04 14:13 UTC
Asas

**Comment by simon-mo** [comment] 2023-12-04 19:06
Currently vLLM doesn't support macOS or windows native. It is currently designed to support NVIDIA with AMD GPU support in progress. 

If you want to use m2 chip right now, I would recommend using llama.cpp for now. 

But we are definitely open for ideas and contributions here! AFIAK, PyTorch's macOS support is pretty behind?

**Comment by pathorn** [comment] 2023-12-22 14:05
Dupe of #1397 

I just made a PR #2244 - feel free to test and give feedback, but this issue should probably be closed as duplicate.

**Comment by bluenevus** [comment] 2024-02-16 19:53
+1

**Comment by hmellor** [comment] 2024-05-31 19:57
Closing in favour of #2081

**Closed by hmellor** 2024-05-31 19:57 UTC
