### ISSUE TITLE
Support YaRN models (RoFormer implementation in rotary_embedding kernel)

### ISSUE THREAD

**Issue by kevaldekivadiya2415** [vllm-project/vllm#1027] opened 2023-09-13 06:19 UTC
Feature request
Nous Research and EleutherAI have recently released the YaRN model, which comes in two versions with context sizes of 64k and 128k. This model utilizes RoFormer-style embeddings, distinguishing it from GPT-NeoX and GPT-J. It is built upon the foundation of the LLaMa 2 model, making it largely compatible with some minor adjustments required for optimal support.

Motivation
The YaRN model's longer context length (up to 128k) is highly valuable for tasks involving extensive context, compared to the limited 4096 context length of the llama2 base model.

Other
YaRN paper: [YaRN: Efficient Context Window Extension of Large Language Models](https://arxiv.org/pdf/2309.00071.pdf)
YaRN Code: [YaRN Github](https://github.com/jquesnelle/yarn)

**Comment by viktor-ferenczi** [comment] 2023-09-22 05:54
It seems to be a duplicate of #980

**Comment by zhongwei1968** [comment] 2023-09-23 05:52
+1

**Comment by hmellor** [comment] 2024-03-08 12:21
Closing as duplicate of #980

**Closed by hmellor** 2024-03-08 12:21 UTC
Labels: duplicate
