### ISSUE TITLE
T5 model support

### ISSUE THREAD

**Issue by havietisov** [vllm-project/vllm#404] opened 2023-07-08 20:07 UTC
Any plans on adding T5 models?
FLAN-T5 are particularly interesting

**Comment by shermansiu** [comment] 2023-08-16 02:06
Yes. See #187. It's also on the dev roadmap (#244).

**Comment by ZSGS-Vipin** [comment] 2023-12-27 07:39
Any updates reg this?

**Comment by shermansiu** [comment] 2023-12-27 09:29
In https://github.com/vllm-project/vllm/issues/187#issuecomment-1825244021, js8544 mentioned that his team would be working on it in November, but no updates have come since then.

**Comment by hmellor** [comment] 2024-03-06 08:58
Closing as duplicate of #187

**Closed by hmellor** 2024-03-06 08:58 UTC
Labels: duplicate, new model
