### ISSUE TITLE
[Bug]: Streaming inference response results cannot be serialized as json normally

### ISSUE THREAD

**Issue by DreamTeamWangbowen** [vllm-project/vllm#4046] opened 2024-04-13 02:41 UTC
### Your current environment

```text
The output of `Postman`
```
...
data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":"!"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":"<"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":"|"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":"im"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":"_"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":"end"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":"|"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":">"},"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-154965d939604267b71cfb09c8c24d38","object":"chat.completion.chunk","created":146773,"model":"/models/Baichuan2-13B-chat-FP16","choices":[{"index":0,"delta":{"content":""},"finish_reason":"stop"}],"usage":{"prompt_tokens":30,"total_tokens":264,"completion_tokens":234}}

data: [DONE]

### 🐛 Describe the bug

https://github.com/vllm-project/vllm/blob/546e7211684a28bbe53088961b4cf5123e235760/vllm/entrypoints/openai/serving_chat.py#L243
https://github.com/vllm-project/vllm/blob/546e7211684a28bbe53088961b4cf5123e235760/vllm/entrypoints/openai/serving_completion.py#L168
https://github.com/vllm-project/vllm/blob/546e7211684a28bbe53088961b4cf5123e235760/vllm/entrypoints/openai/serving_completion.py#L268
This final output of [DONE] is of little use to the client, and the receiving end cannot process the data format normally.

So we should be able to delete it so that the client can process streaming inference results more conveniently.

**Comment by DreamTeamWangbowen** [comment] 2024-04-13 02:46
@WoosukKwon Hi,brother,I have observed that other streaming reasoning response interfaces do not have the special ending flag [DONE].

**Comment by ywang96** [comment] 2024-04-13 04:16
The goal of the Open AI API server is to match the same functionality of OpenAI endpoint, and this is how currently OpenAI does it as well. See https://github.com/openai/openai-python/blob/595e6b834fe26e08e9ac5415ab15bc19b8661f2c/src/openai/types/completion_create_params.py#L158

**Comment by simon-mo** [comment] 2024-04-13 04:29
Hi @DreamTeamWangbowen, the last message is as specified by OpenAI streaming protocol. 

https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream

**Comment by ywang96** [comment] 2024-04-14 04:24
Closing this since it is not a bug.

**Closed by ywang96** 2024-04-14 04:24 UTC
Labels: bug

**Comment by mechigonft** [comment] 2024-04-26 01:53
I want to learn your streaming inference script
