### ISSUE TITLE
Inquiry Regarding vLLM Support for Mac Metal API

### ISSUE THREAD

**Issue by yihong1120** [vllm-project/vllm#2081] opened 2023-12-13 08:50 UTC
Dear vLLM Maintainers,

I hope this message finds you well. I am reaching out to inquire about the potential for integrating Mac Metal API support within the vLLM framework. As an avid user and advocate for vLLM's capabilities, I have been thoroughly impressed with its performance and flexibility across various platforms and hardware configurations.

Given the increasing prevalence of Mac devices in the machine learning community and the performance benefits offered by Apple's Metal API for GPU-accelerated computing, I am curious to know if there are any plans to extend vLLM's compatibility to include Metal support. This would undoubtedly be a significant boon for researchers and developers working on Mac environments who wish to leverage vLLM's impressive suite of features.

Could you please shed some light on the following aspects:

1. Are there any ongoing efforts or discussions around incorporating Metal API support into vLLM?
2. If such plans are in the pipeline, what is the anticipated timeline for the availability of this feature?
3. How might the community contribute to expediting this process, and are there specific areas where contributions are most needed?

I understand that integrating a new backend such as Metal may present a variety of challenges, but I believe the potential benefits to the user community could be substantial. I am keen to offer my assistance, whether it be through testing, development, or documentation, to help bring this capability to fruition.

Thank you for your time and consideration. I eagerly await your response and am excited about the prospect of further enhancing vLLM's accessibility and performance on Mac platforms.

Best regards,
yihong1120

**Comment by jagtesh** [comment] 2024-02-02 21:25
> Torch has [officially supports Metal](https://developer.apple.com/metal/pytorch/) for a while now. Would adding support in vLLM be as simple as removing changing `device="cuda"` to "mps" on Macs? Are there any other dependencies on CUDA?

Anyone? I'd be happy to do this - just don't want to spend hours down a dead-end.

**Comment by C0deMunk33** [comment] 2024-02-06 17:51
I'd like to see this work as well, lots of Metal out there

**Comment by bluenevus** [comment] 2024-02-16 19:51
same here please

**Comment by nostaljic** [comment] 2024-04-13 02:57
Wish it could be implemented🥺

**Comment by jagtesh** [comment] 2024-04-14 04:35
My offer still stands if someone on the project can answer the above questions.

**Comment by hmellor** [comment] 2024-04-18 11:34
@pathorn says they have an implementation that runs on M3 chips in https://github.com/vllm-project/vllm/issues/176#issuecomment-2023827553

Do you think it could be adapted to the new CPU backend that was added in #3634?

**Comment by jagtesh** [comment] 2024-04-19 16:54
> @pathorn says they have an implementation that runs on M3 chips in [#176 (comment)](https://github.com/vllm-project/vllm/issues/176#issuecomment-2023827553)
> 
> Do you think it could be adapted to the new CPU backend that was added in #3634?

FYI for anyone who wants to see that PR: https://github.com/vllm-project/vllm/pull/2244#issuecomment-1868419884. @pathorn did some tremendous work on the PR. However, llama.cpp still performs faster - by a mile. This may not be a fruitful endeavour after all.

**Comment by hmellor** [comment] 2024-09-20 20:29
Closing because other projects such as llama.cpp are more appropriate for running LLMs on Apple silicon.

**Closed by hmellor** 2024-09-20 20:29 UTC

**Comment by baggiponte** [comment] 2024-10-01 09:24
> Closing because other projects such as llama.cpp are more appropriate for running LLMs on Apple silicon.

I agree it makes sense, but I would not be super concerned by the performance. I have a M3 Mac provided by my company and the development loop is really slow when it comes to vLLM. Despite suboptimal, I'd love to just be able to run `[uv] pip install vLLM` and be free to experiment locally, then push to prod.

**Comment by RobotSail** [comment] 2024-10-25 03:06
Also want to +1 this idea, it would be much cheaper to buy a 192GB Apple Silicon machine to run full Mixtral 8x7B than shelling out the money for an NVIDIA rig with equivalent memory.

**Comment by skyzh** [comment] 2025-02-01 05:25
Hi all, I have a draft patch to try integrating vLLM with Metal. It runs, but unfortunately, it doesn't produce any reasonable result, probably due to MPS<->CPU data movement and fallbacks. So I've submitted the patch and marked it a draft, in case someone can help :)

https://github.com/vllm-project/vllm/pull/12640

**Comment by arthurgousset** [comment] 2025-02-05 14:53
+1 this would be great!

**Comment by albertocavalcante** [comment] 2025-03-13 15:18
@hmellor any chance it can be reconsidered? Thanks

**Comment by exdysa** [comment] 2025-03-18 21:07
> vLLM already supports Mac on CPU https://docs.vllm.ai/en/latest/getting_started/installation/cpu.html?device=apple
> 
> This should be adequate because:
> 
> * I recall reading in PyTorch issues that MPS has precision issues (I'm unsure if they have been resolved yet)
> * Anecdotally, I have found that models tend to run faster on my Mac's CPU anyway

Any training op will certainly not be faster. I don't know what cpu you have but on an M3 and M4 there is certainly a difference. Please provide benchmarks if you still disagree.

Why this over llama_cpp? This supports more multimodal things and is more robust, and I would love to take advantage of vllm developments and integrate it into my projects. 

From what I can tell an extensive assortment of operations are available in PyTorch. I would urge you to take a look at [this Pytorch issue](https://github.com/pytorch/pytorch/issues/77764) for further proof of MPS interest and significant development. In my experience, most ops are pretty simple to adapt for supporting CUDA and MPS platforms.

If skyzh is already working on this, I would love to help provide a PR.

**Comment by skyzh** [comment] 2025-03-18 21:29
The main blockers are:

1. MPS precision issues - models don't give sensible results with MPS at all due to PyTorch/MPS bugs.
2. vllm is unlikely to be faster on computation than other highly optimized implementation on metal - PyTorch does not support unified memory architecturally.
3. Custom operators - vllm implements a lot of custom PyTorch operators that need to be reimplemented in metal. This is a significant amount of work. Otherwise things fallback to CPU and because of (2) it incurs large copy overheads.

Plus I don't think the current vllm GPUWorker is designed for unified memory either, and MPS needs a new worker to ensure adequate performance.

TL;DR it will take a significant amount of work to make vllm metal run faster than vllm CPU; and it's not possible for vllm to unlock the full potential of M-series chips' unified memory architecture as it depends on PyTorch.

**Comment by exdysa** [comment] 2025-03-18 22:37
Thank you for the quick reply! It sounds like would be a lot of work for little gain, though I am curious about this one:

> 1. MPS precision issues - models don't give sensible results with MPS at all due to PyTorch/MPS bugs.

Have you reproduced this in projects other than vLLM? I believe you, I just haven't experienced this, save for MLX conversions

**Comment by kulinseth** [comment] 2025-04-06 19:28
Folks, We can help on MPS issues and providing support for vllm. What's are the networks / commands we would like to target on Mac platforms for vllm ?

**Comment by hmellor** [comment] 2025-04-06 20:25
@kulinseth you could probably work with @skyzh to get https://github.com/vllm-project/vllm/pull/12640 producing reasonable output
