### ISSUE TITLE
[Model]: Support for Qwen-VL model

### ISSUE THREAD

**Issue by wsp317** [vllm-project/vllm#7192] opened 2024-08-06 07:22 UTC
### 🚀 The feature, motivation and pitch

Thank you for considering support for the Qwen-VL-Chat model.
Qwen-VL-Chat is more flexible in situations that users could upload several images in different conversation turns compared to its competitor with similar model size.

**Comment by alex-jw-brooks** [comment] 2024-08-07 18:18
I am looking into adding support for image inputs for Qwen-VL/Qwen-VL-Chat 😄

**Comment by hmellor** [comment] 2024-08-27 09:43
Closing as duplicate of #962

**Closed** 2024-09-05 12:48 UTC
Labels: new model
