### ISSUE TITLE
GPTQ / Quantization support?

### ISSUE THREAD

**Issue by nikshepsvn** [vllm-project/vllm#174] opened 2023-06-21 02:40 UTC
Will vLLM support 4-bit GPTQ models?

**Comment by WoosukKwon** [comment] 2023-06-21 03:26
Thanks for the feature request! Quantization is not currently supported, but it's definitely on our roadmap. Please stay tuned.

**Comment by nikshepsvn** [comment] 2023-06-22 01:19
How do I best go about tracking this? Is there a discord or public roadmap somewhere I can look at?

**Comment by faamir** [comment] 2023-08-13 14:25
Any update for GPTQ support?

**Comment by Symbolk** [comment] 2023-08-15 06:13
> How do I best go about tracking this? Is there a discord or public roadmap somewhere I can look at?

See Roadmap here: https://github.com/vllm-project/vllm/issues/244

**Comment by chu-tianxiang** [comment] 2023-08-23 14:02
I looked into this a bit today and it seems straight forward to integrate [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ) into vllm, so I implemented a draft for LLaMA (see this [commit](https://github.com/chu-tianxiang/vllm/commit/71dfb52796b5b40fb724fe1f8cb26463c245b084)) and did a few benchmarks on single A100-80G. I don't know why but It's slower than expected.

```
python benchmark_throughput.py --model TheBloke/Llama-2-13B-chat-GPTQ --dataset ShareGPT_V3_unfiltered_cleaned_split.json
```

|  Model   | Throughout (requests/s)  | Throughout (tokens/s)  |
|  ----  | ----  | ----  |
| meta-llama/Llama-2-13b-chat-hf  | 4.00 | 1915 |
| TheBloke/Llama-2-13B-chat-GPTQ  | 3.32 | 1587 |
| TheBloke/Llama-2-70B-chat-GPTQ  | 1.09 | 519 |

**Comment by osilverstein** [comment] 2023-08-25 05:39
> I looked into this a bit today and it seems straight forward to integrate [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ) into vllm, so I implemented a preliminary version for LLaMA (see this [commit](https://github.com/chu-tianxiang/vllm/commit/71dfb52796b5b40fb724fe1f8cb26463c245b084)) and did a few benchmarks on single A100-80G. I don't know why but It's slower than expected.
> 
> ```
> python benchmark_throughput.py --model TheBloke/Llama-2-13B-chat-GPTQ --dataset ShareGPT_V3_unfiltered_cleaned_split.json
> ```
> 
> Model	Throughout (requests/s)	Throughout (tokens/s)
> meta-llama/Llama-2-13b-chat-hf	4.00	1915
> TheBloke/Llama-2-13B-chat-GPTQ	3.32	1587
> TheBloke/Llama-2-70B-chat-GPTQ	1.09	519

what's the baseline with normal version?

**Comment by chu-tianxiang** [comment] 2023-08-26 15:59
As an update, I added tensor parallel QuantLinear layer and supported most AutoGPT compatible models  in [this branch](https://github.com/vllm-project/vllm/compare/main...chu-tianxiang:vllm-gptq:gptq). The code has not been thoroughly tested yet because the combinations of model architectures and GPTQ settings are way too many.

**Comment by AchtungBaguette** [comment] 2023-09-14 12:27
@chu-tianxiang do you keep track with vLLM team work ? I saw that the revision param in EngineArgs was implemented, which would be more than helpful on your branch 🙏

**Comment by singularity-sg** [comment] 2023-09-29 01:52
@chu-tianxiang I tried forking your `vllm-gptq` branch and was successful deploying the `TheBloke/Llama-2-13b-Chat-GPTQ` model. However, when I tried the `TheBloke/Llama-2-7b-Chat-GPTQ` model, it threw the following exception whenever I made a query to the model. I wonder if the issue is with the model itself or something else. I'll dig further into this when I have the chance but it's likely the Sampler was generating the probability tensor with invalid values

```
INFO:     13.229.18.8:52663 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/vllm-gptq/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/home/ubuntu/vllm-gptq/vllm/engine/async_llm_engine.py", line 351, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/engine/async_llm_engine.py", line 330, in engine_step
    request_outputs = await self.engine.step_async()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/engine/async_llm_engine.py", line 191, in step_async
    output = await self._run_workers_async(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/engine/async_llm_engine.py", line 220, in _run_workers_async
    all_outputs = await asyncio.gather(*all_outputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.3/lib/python3.11/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayTaskError(RuntimeError): ray::RayWorker.execute_method() (pid=68296, ip=172.31.40.30, actor_id=3b90ca9f90ebf20a67ae6c2c01000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7ef09122dad0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/vllm-gptq/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/worker/worker.py", line 305, in execute_model
    output = self.model(
             ^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/vllm-gptq/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/model_executor/models/llama.py", line 296, in forward
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/vllm-gptq/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/model_executor/layers/sampler.py", line 85, in forward
    return _sample(probs, logprobs, input_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/model_executor/layers/sampler.py", line 451, in _sample
    sample_results = _random_sample(seq_groups, is_prompts,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/vllm-gptq/vllm/model_executor/layers/sampler.py", line 342, in _random_sample
    random_samples = torch.multinomial(probs,
                     ^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by wejoncy** [comment] 2023-10-25 11:27
Hi,
If anyone wants try GPTQ quantizationo in vLLM.
Please use this repo [QLLM](https://github.com/wejoncy/QLLM) to quantize model(LLama) and it would compatiable AWQ in vLLM.
And Of courcr you can select AWQ to quantize it as well.

**Comment by CWG-filip** [comment] 2023-12-09 23:23
> Hi, If anyone wants try GPTQ quantizationo in vLLM. Please use this repo [QLLM](https://github.com/wejoncy/QLLM) to quantize model(LLama) and it would compatiable AWQ in vLLM. And Of courcr you can select AWQ to quantize it as well.

Something is off with this QLLM gptq quantization... all the dependencies aren't specified in requirements file. Also, 3 times tried quantizing and every time it breaks when it tries to save the file or quant is done. Tried Llama2-70b and mistral 7b

<img width="761" alt="Screenshot 2023-12-09 at 15 21 57" src="https://github.com/vllm-project/vllm/assets/72705346/f9bd9dc1-a407-436c-a39e-d859d043d4ce">

**Comment by wejoncy** [comment] 2023-12-10 02:04
> > Hi, If anyone wants try GPTQ quantizationo in vLLM. Please use this repo [QLLM](https://github.com/wejoncy/QLLM) to quantize model(LLama) and it would compatiable AWQ in vLLM. And Of courcr you can select AWQ to quantize it as well.
> 
> Something is off with this QLLM gptq quantization @wejoncy ... all the dependencies aren't specified in requirements file. Also, 3 times tried quantizing and every time it breaks when it tries to save the file or quant is done. Tried Llama2-70b and mistral 7b

Hi,
 Thanks for try this out and sorry for the inconvenient. This bug has been fixed in latest:main.
For now, you can have too ways to use GPTQ quant method in vLLM with qllm tool.

1. such as Llama-families, convert to AWQ ifi you didn't enable act_order and set bits==4 and there is no mix bits inside.
2. use GPTQ directly. But the GPTQ branch in vLLM is on the way merged.

**Comment by jacobwarren** [comment] 2024-02-02 05:29
Is there any update for 8bit support? That would help Mixtral generate useable outputs on a single (non-overpriced) GPU.

**Comment by hmellor** [comment] 2024-02-02 17:48
I have successfully used both GPTQ and AWQ models with vLLM.

Should this issue be considered solved @WoosukKwon?

**Comment by jacobwarren** [comment] 2024-02-03 22:10
@hmellor it currently works with 4-bit, but not 8-bit. Currently you have to use chu-tianxiang/vllm-gptq to get 8-bit support.

**Closed** 2024-03-06 09:01 UTC
Labels: feature request

**Comment by SuperBruceJia** [comment] 2024-06-27 21:22
Is vLLM well-supporting the int-2 GPTW models? 

Thank you very much!

**Comment by SuperBruceJia** [comment] 2024-06-27 21:23
@hmellor @singularity-sg @jacobwarren @wejoncy @Symbolk @WoosukKwon
