### ISSUE TITLE
AWQ Support 

### ISSUE THREAD

**Issue by allzero-kwon** [vllm-project/vllm#1488] opened 2023-10-27 06:41 UTC
I got this error to run awq model with VLLM on a v100 gpu.
How can i resolve this ? 

```
The quantization method awq is not supported for the current GPU. Minimum capability: 75. Current capability: 70.
```

**Comment by casper-hansen** [comment] 2023-10-27 17:20
It is recommended to use a GPU with the Ampere architecture. V100 is not supported.

**Comment by WoosukKwon** [comment] 2023-11-19 07:54
Closed as it is a duplicate of #1345

**Closed by WoosukKwon** 2023-11-19 07:54 UTC
Labels: duplicate
