### ISSUE TITLE
“RuntimeError: probability tensor contains either `inf`, `nan` or element < 0” when use llama2-70B 

### ISSUE THREAD

**Issue by EasonLi24** [vllm-project/vllm#1448] opened 2023-10-23 06:49 UTC
When I use llama2-70B and set 'tensor_parallel_size=8' get “RuntimeError: probability tensor contains either `inf`, `nan` or element < 0”, but when I use same code but replace model to gpt-neox or llama2-7B it work.

When I use llama2-70B but set 'tensor_parallel_size=4'  it also work. And I use 8xA100 for my experiment. 

Can someone give me any ideas about llama2-70B?

Here is my code:

```python
from vllm import LLM, SamplingParams
import torch

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]

sampling_params = SamplingParams(temperature=0, max_tokens=300)

model_dir = "../llama70B"
llm = LLM(model=model_dir, trust_remote_code=True, tensor_parallel_size=8)

outputs = llm.generate(prompts, sampling_params)
```

**Comment by gesanqiu** [comment] 2023-10-25 09:56
revert vllm version to 0.2.0 should fix this problem.

**Comment by viktor-ferenczi** [comment] 2023-11-04 04:56
Likely a duplicate of #641

**Comment by EasonLi24** [comment] 2023-11-09 07:20
> Likely a duplicate of #641

Yes, but the pr for IntrenLM seems not work for Llama2-70B because bias in llama is set to False defult.

**Comment by hmellor** [comment] 2024-03-13 12:56
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Closed by hmellor** 2024-03-13 12:56 UTC

**Comment by ayrnb** [comment] 2024-09-24 09:40
I also encountered the same problem, how can I solve it?  vllm 0.2.1.post
