### ISSUE TITLE
Running multiple cards in parallel is slower(nearly twice) than a single card

### ISSUE THREAD

**Issue by Amanda-Barbara** [vllm-project/vllm#935] opened 2023-09-03 02:40 UTC
Hi, when I am running four A100 with parameter tensor_parallel_size is 4 in parallel, I found that the speed  is slower(nearly twice) than a single card. can you explain what causes this and how to solve it. Thank you.

**Comment by dutsc** [comment] 2023-09-07 03:15
I use 3090 and had the same problem as you.

**Comment by hmellor** [comment] 2024-03-08 11:13
Closing as duplicate of #689

**Closed by hmellor** 2024-03-08 11:13 UTC
Labels: duplicate
