### ISSUE TITLE
Mixtral keeps crashing vLLM.  max() arg is an empty sequence then SIGABRT

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#2476] opened 2024-01-18 02:52 UTC
```
export CUDA_HOME=/usr/local/cuda-12.3
export PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cu123"
pip install git+https://github.com/vllm-project/vllm.git
pip install mosaicml-turbo --upgrade
pip install git+https://github.com/stanford-futuredata/megablocks.git
pip install fschat==0.2.34
```

```
export CUDA_VISIBLE_DEVICES=6,7
python -m vllm.entrypoints.openai.api_server --port=5002 --host=0.0.0.0 --model mistralai/Mixtral-8x7B-Instruct-v0.1 --seed 1234 --tensor-parallel-size=2 --max-num-batched-tokens=153600
```

Sometimes there are aborted generations:
```
INFO 01-18 01:53:25 async_llm_engine.py:134] Aborted request cmpl-2b7bd3e1f8cb434e9f98e8b3ea2c58e6.
```

But at some point, every day, we hit this:
```
INFO 01-18 06:58:46 async_llm_engine.py:384] Received request cmpl-dfb5d2e7322a4697b8a0184901953e56: prompt: '<s> [INST] MATCH DETAILS\n- Tournament: NBA\n- Sport: Basketball\n- Season: NBA 23/24\n- HomeTeam: Detroit Pistons\n- AwayTeam: Minnesota Timberwolves>
INFO 01-18 06:58:47 async_llm_engine.py:134] Aborted request cmpl-6bd865032aef41c6b135d86278e38264.
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7f2546afeef0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f254408e9b0>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7f2546afeef0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f254408e9b0>)>
Traceback (most recent call last):
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 364, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 343, in engine_step
    request_outputs = await self.engine.step_async()
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 190, in step_async
    all_outputs = await self._run_workers_async(
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 231, in _run_workers_async
    all_outputs = await asyncio.gather(*coros)
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/worker/worker.py", line 197, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 448, in execute_model
    self.prepare_input_tensors(seq_group_metadata_list))
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 342, in prepare_input_tensors
    ) = self._prepare_decode(seq_group_metadata_list)
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 192, in _prepare_decode
    max_context_len = max(context_lens)
ValueError: max() arg is an empty sequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
```

Once this happens, things start to really drag and some generations complete, but no new ones do.  Totally stuck from client experience.

Eventually, most of time things totally crash after this, maybe in 30 minutes of being of bad state:

```
INFO 01-18 07:29:03 llm_engine.py:807] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%
INFO:     38.128.232.144:34135 - "POST /v1/completions HTTP/1.1" 200 OK
INFO 01-18 07:29:06 async_llm_engine.py:384] Received request cmpl-05ab2025a6f24c549c96a9c188000d98: prompt: '<s> [INST] Who are you and what do you do? [/INST]</s> [INST] economic chnages in the industrial revolution [/INST]</s> [INST] environmental changes i>
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4272075, OpType=BROADCAST, NumelIn=20, NumelOut=20, Timeout(ms)=1800000) ran for 1800824 milliseconds b>
[2024-01-18 07:29:07,017 E 800806 808293] logging.cc:97: Unhandled exception: St13runtime_error. what(): [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4272075, OpType=BROADCAST, >
[2024-01-18 07:29:07,028 E 800806 808293] logging.cc:104: Stack trace: 
 /home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/ray/_raylet.so(+0xf199fa) [0x7f2545e239fa] ray::operator<<()
/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/ray/_raylet.so(+0xf1c1b8) [0x7f2545e261b8] ray::TerminateHandler()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa37c) [0x7f265a01237c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3e7) [0x7f265a0123e7]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa36f) [0x7f265a01236f]
/home/fsuser/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so(+0xc86f5b) [0x7f26155a1f5b] c10d::ProcessGroupNCCL::ncclCommWatchdog()
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6df4) [0x7f265a03edf4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f2695c56609] start_thread
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f2695a21133] __clone

*** SIGABRT received at time=1705543147 on cpu 4 ***
PC: @     0x7f269594500b  (unknown)  raise
    @     0x7f2695c62420       4048  (unknown)
    @     0x7f265a01237c  (unknown)  (unknown)
    @     0x7f265a012090  (unknown)  (unknown)
[2024-01-18 07:29:07,029 E 800806 808293] logging.cc:361: *** SIGABRT received at time=1705543147 on cpu 4 ***
[2024-01-18 07:29:07,029 E 800806 808293] logging.cc:361: PC: @     0x7f269594500b  (unknown)  raise
[2024-01-18 07:29:07,029 E 800806 808293] logging.cc:361:     @     0x7f2695c62420       4048  (unknown)
[2024-01-18 07:29:07,029 E 800806 808293] logging.cc:361:     @     0x7f265a01237c  (unknown)  (unknown)
[2024-01-18 07:29:07,029 E 800806 808293] logging.cc:361:     @     0x7f265a012090  (unknown)  (unknown)
Fatal Python error: Aborted
```

During this entire time, there is plenty of GPU memory, only 60GB/80GB is used on 8*H100.  But during this bad state time, 100% of GPU is used, even though no generations get through.  The system has plenty of memory, about 1.5TB and plenty is free at the time.  There are no hardware issues mentioned in dmesg.

So I think this is pure vLLM bug.

After restarting vLLM, all seems fine, we can do hard tests, various long context, async, etc. and no issues.

**Comment by pseudotensor** [comment] 2024-01-18 02:55
Perhaps related:

https://github.com/vllm-project/vllm/issues/1783
https://github.com/vllm-project/vllm/issues/2475

**Comment by NikolaBorisov** [comment] 2024-01-18 06:01
I see the same issue with the latest vllm. Older versions from about Dec 20-th was running ok.

**Comment by pseudotensor** [comment] 2024-01-18 06:43
I tried doign what Issue #1783 said about not approaching max sequence length, but didn't help.  At 31k only ever tried for input + output, still crashing.

**Comment by NikolaBorisov** [comment] 2024-01-18 23:35
I just got this exception again, in CodeLlama model. It is not limited to just Mixtral.

**Comment by pseudotensor** [comment] 2024-01-18 23:38
I also tried just using 65k batched tokens, same problem.

**Comment by cadedaniel** [comment] 2024-01-19 04:02
I think it's caused by the bug fixed in https://github.com/vllm-project/vllm/pull/2463. that could allow for a sequence group to be running but also have no running sequences.

**Comment by DaBossCoda** [comment] 2024-01-22 07:44
same issue here

**Comment by simon-mo** [comment] 2024-01-23 19:18
I'm closing this assuming #2463 fixes this. Try using latest vLLM? If this still happens, please feel free to re-open.

**Closed by simon-mo** 2024-01-23 19:18 UTC

**Comment by NikolaBorisov** [comment] 2024-01-24 02:16
Seems to work with the latest.
