### ISSUE TITLE
[Usage]: Out of Memory w/ multiple models

### ISSUE THREAD

**Issue by yudataguy** [vllm-project/vllm#4678] opened 2024-05-08 08:37 UTC
### Your current environment

```text
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU 
```

### How would you like to use vllm

I'm running a eval framework that's evaluating multiple models. vllm doesn't seem to free the gpu memory after initialize the 2nd model (with the same variable name), how to free up gpu memory with each vLLMEngine call ``` llm = LLM(new_model) ```

**Comment by jiqing-feng** [comment] 2024-05-13 07:26
Same issue.

**Comment by russellb** [comment] 2024-10-16 19:19
the LLM engine internal to the LLM class should get destroyed when your `LLM` instance is garbage collected. You could try forcing that with `del(llm)`.

**Comment by russellb** [comment] 2024-10-16 19:20
more detailed input on this in #3281

**Comment by russellb** [comment] 2024-10-16 19:27
going to close this since it's a duplicate of #3281

**Closed by russellb** 2024-10-16 19:27 UTC
Labels: usage
