### ISSUE TITLE
[New Model]: CohereForCausalLM Support request 

### ISSUE THREAD

**Issue by yydxlv** [vllm-project/vllm#3546] opened 2024-03-21 06:11 UTC
### The model to consider.

ValueError: Model architectures ['CohereForCausalLM'] are not supported for now

![1711001492046](https://github.com/vllm-project/vllm/assets/7098003/c9f431ec-bb69-4903-9bdd-0073fef03ade)

**Comment by simon-mo** [comment] 2024-03-21 06:17
Duplicate of #3330

**Closed by simon-mo** 2024-03-21 06:17 UTC
Labels: new model
