### ISSUE TITLE
Aborted request without reason

### ISSUE THREAD

**Issue by erjieyong** [vllm-project/vllm#2484] opened 2024-01-18 08:48 UTC
Hi, i am trying to load test vllm on a single gpu with 20 concurrent request. Each request would pass through the llm engine twice. Once to change the prompt, the other to generate the output.

However, normally only between 6 - 10 requests finished successfully. The remaining requests would normally just be displayed as "Aborted request" without any error logs or trace. GPU KV cache can be up to 95% for those sequences which finished successfully.

```
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request 0e89f1d2d94c4a039f868222c100cc8a.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request be67046b843244b5bf1ed3d2ff2f5a02.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request b532ed57647945869a4cae499fe54f23.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request 6c56897bbc9d4a808b8e056c39baf91b.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request 75b645c69d7449509f68ca23b34f1048.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request eb87d6473a9d4b3699ca0cc236900248.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request ca15a251849c45329825ca95a2fce96b.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request c42bbea2f781469e89e576f98e618243.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request 14b94d4ffd6646d69d4c2ad36d7dfd50.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request 83c7dd9cbe9d4f6481b26403f46f1731.
INFO 01-17 03:11:25 async_llm_engine.py:134] Aborted request 3e98245d88534c53be230aa25c56d99a.
INFO 01-17 03:11:26 async_llm_engine.py:111] Finished request 49b84ef96af44f069056b2fc43526cdd.
```

I have been trying to find ways to find out what's the cause of the abortion without success. Appreciate any help. Thanks!

My code to load the engine is as follows:
```
engine_args = AsyncEngineArgs(
    model=LLM_BASEMODEL,
    tokenizer=LLM_BASEMODEL,
    tokenizer_mode="auto",
    trust_remote_code=True,
    download_dir=None,
    load_format="auto",
    dtype="auto",
    seed=0,
    max_model_len=None,
    worker_use_ray=False,
    pipeline_parallel_size=1,
    tensor_parallel_size=1,
    max_parallel_loading_workers=None,
    block_size=16,
    swap_space=4,
    gpu_memory_utilization=0.9,
    max_num_batched_tokens=None,
    max_num_seqs=256,
    max_paddings=256,
    disable_log_stats=False,
    revision=None,
    tokenizer_revision=None,
    quantization="gptq",
    enforce_eager=False,
    max_context_len_to_capture=8192,
    engine_use_ray=False,
    disable_log_requests=False,
    max_log_len=None,
)
engine = AsyncLLMEngine.from_engine_args(engine_args)
```

**Comment by ARayOfsunshine** [comment] 2024-01-20 04:00
mark

**Comment by HermitSun** [comment] 2024-01-30 11:00
+1. And the HTTP status code is 200. It's weird.

**Comment by CoLdIcE42** [comment] 2024-01-30 15:22
+1

**Comment by erjieyong** [comment] 2024-02-06 08:31
For my case, I've managed to identify that the issue is not due to vllm. Reason because i am able to call my backend api directly using the server ip address without any aborted request. In comparison, if i were to call the backend api using my domain, i will face this aborted request issue. 

My suspicion is that nginx is meddling with the configuration but have yet to find the fix yet.

**Comment by vecorro** [comment] 2024-02-26 00:57
Same here with vLLM v.0.3.0:

```
INFO 02-25 12:13:05 llm_engine.py:877] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 62.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.5%, CPU KV cache usage: 0.0%
INFO 02-25 12:13:10 llm_engine.py:877] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 62.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 5.7%, CPU KV cache usage: 0.0%
INFO 02-25 12:13:11 async_llm_engine.py:133] Aborted request cmpl-4ed3ef5554c44cd98158a194a4439744.
INFO 02-25 12:13:12 async_llm_engine.py:431] Received request cmpl-5ed32b9b9ff645718b4794cfe2cb37b0: prompt
```

**Comment by ghpu** [comment] 2024-03-08 15:52
Same here, when sending 4 request to a mistral instruct 7B v0.2 on a single nvidia A40. Occurs both with default swap-size and swap-size=0.

**Comment by prakashsanker** [comment] 2024-03-28 21:42
Confirmed - this happens for me as well, with latest vllm. This time serving Mixtral 8x7b with AWQ. Doesn't happen for all prompts and it seems to happen more often when hitting `completions` rather than `chat/completions`.

**Comment by prakashsanker** [comment] 2024-04-02 20:23
Ok so - 
1. This is a clear problem with the implementation of the inference server, rather than the core vllm engine. I had a prompt that was consistently failing when hitting the open ai compatible server. 
2. I copied/pasted the prompt and ran it with offline inference --> the prompt worked.

**Comment by prakashsanker** [comment] 2024-04-03 17:27
@simon-mo just tagging you here to investigate.

**Comment by simon-mo** [comment] 2024-04-03 18:59
cc @njhill

**Comment by br3no** [comment] 2024-04-16 14:57
Is there any indication of an exception in the response?

There are a few places in `async_llm_engine.py` that call this method and exceptions are placed into the request stream but not logged out in the server.

**Comment by ptsand** [comment] 2024-04-17 12:31
Did some more testing and debugging, I can recreate the error quickly by running multiple prompts async. The calling code cannot receive any response body:

```
2024-04-17 14:11:30,767 [INFO] [_client.py:1729] HTTP Request: POST https://[BASE_URL]/v1/chat/completions "HTTP/1.1 200 OK"
2024-04-17 14:11:30,768 [DEBUG] [_trace.py:85] receive_response_body.started request=<Request [b'POST']>
2024-04-17 14:11:47,340 [DEBUG] [_trace.py:85] receive_response_body.failed exception=ReadError(BrokenResourceError())
2024-04-17 14:11:47,340 [DEBUG] [_trace.py:85] response_closed.started
2024-04-17 14:11:47,341 [DEBUG] [_trace.py:85] response_closed.complete
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/anyio/streams/tls.py", line 196, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/anyio/streams/tls.py", line 138, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1212, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_transports/default.py", line 249, in __aiter__
    async for part in self._httpcore_stream:
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 361, in __aiter__
    async for part in self._stream:
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_async/http11.py", line 337, in __aiter__
    raise exc
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_async/http11.py", line 329, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_async/http11.py", line 198, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/mistralai/async_client.py", line 125, in _request
    async for line in response.aiter_lines():
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_models.py", line 966, in aiter_lines
    async for text in self.aiter_text():
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_models.py", line 953, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_models.py", line 932, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_models.py", line 990, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_transports/default.py", line 248, in __aiter__
    with map_httpcore_exceptions():
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sand/Capacit/seek/seek-api-telia/src/api/controllers/v1/conversation.py", line 147, in __acall__
    async for event in handler_method(request):
  File "/Users/sand/Capacit/seek/seek-api-telia/src/api/controllers/v1/conversation.py", line 235, in create_message
    async for token in stream:
  File "/Users/sand/Capacit/seek/seek-api-telia/src/infrastructure/resolvers/prompt_resolver.py", line 73, in astreamer
    async for message in generator:
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 305, in astream
    raise e
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 287, in astream
    async for chunk in self._astream(
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/langchain_mistralai/chat_models.py", line 369, in _astream
    async for chunk in await acompletion_with_retry(
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/mistralai/async_client.py", line 261, in chat_stream
    async for json_response in async_response:
  File "/opt/homebrew/anaconda3/envs/seek/lib/python3.11/site-packages/mistralai/async_client.py", line 143, in _request
    raise MistralException(f"Unexpected exception ({e.__class__.__name__}): {e}") from e
mistralai.exceptions.MistralException: Unexpected exception (ReadError):

500: Internal Server Error during event handling.
```

**Comment by cocoza4** [comment] 2024-04-18 07:41
I also got the same error. This is what I ran
```
python3 -u -m vllm.entrypoints.openai.api_server \
       --host 0.0.0.0 \
       --model casperhansen/mixtral-instruct-awq \
       --tensor-parallel-size 4 \
      --enforce-eager \
      --quantization awq \
      --gpu-memory-utilization 0.96
```

Any solution?

**Comment by davidgxue** [comment] 2024-04-19 19:08
Having the same issue with more than 100 concurrent requests at a time.

**Comment by ArnaudHureaux** [comment] 2024-04-23 15:34
No explanations ? Can it be about a lack of GPU memory ?
Or is it because i increased the --max-model-len to 32768 ?

**Comment by ptsand** [comment] 2024-04-24 06:31
It seems to be much worse when increasing the load. I don't think it's GPU memory cause I needed to reduce max-model-len to avoid getting out of memory errors running on 2 nvidia A10 GPUs (24 GB memory). 

It is running very slowly (unusable I would say) when I run my load tests on it where I simulate up to 40 humans prompting at 40 words per minute.

If anyone knows approximately when vLLM is getting optimized for AWQ models and how big a perfomance increase is expected I would be very happy to know!

**Comment by br3no** [comment] 2024-04-24 06:55
Let’s recap the issue discussion until now:
It happens with different models. It happens with different GPUs. It happens with different quantization methods. It happens on high load. 

@prakashsanker’s hypothesis is that this is an issue with the server and not the core engine. I believe he is right.

Maybe someone here is knowledgeable about asynchronous webserving in Python and has time to investigate? 

I suppose the expected behaviour would be for the server to start returning 503 once it can’t handle more requests.

**Comment by RoacherM** [comment] 2024-04-25 03:20
Same promblem with llama3-70b-instruct version. It works fine when max_token set to 200, but failed when set to 1000 or other larger number.

`bash
INFO 04-25 11:17:52 metrics.py:218] Avg prompt throughput: 1.7 tokens/s, Avg generation throughput: 5.0 tokens/s, Running: 1 req
|start_header_id|>user<|end_header_id|>\n\n如何用python实现一个quick sort，永远用中文回复<|eot_id|><|start_header_id|>as[23/201]
|end_header_id|>\n\n', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_p
enalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stoppin
g=False, stop=[], stop_token_ids=[128001, 128009], include_stop_str_in_output=False, ignore_eos=False, max_tokens=500, min_token
s=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: [1280
00, 128000, 128006, 882, 128007, 271, 109425, 11883, 12958, 112026, 48044, 28863, 3460, 3922, 105243, 106297, 11883, 108891, 189
04, 59464, 128009, 128006, 78191, 128007, 271], lora_request: None.
INFO 04-25 11:17:27 metrics.py:218] Avg prompt throughput: 5.0 tokens/s, Avg generation throughput: 3.2 tokens/s, Running: 1 req
s, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 04-25 11:17:32 metrics.py:218] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.1 tokens/s, Running: 1 re
qs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 04-25 11:17:37 metrics.py:218] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 18.1 tokens/s, Running: 1 re
qs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
INFO 04-25 11:17:41 async_llm_engine.py:154] Aborted request cmpl-31b9088b64b24ecbadaaf6ab0d99cc9b.
`

**Comment by davidgxue** [comment] 2024-04-25 04:39
I think the problem I was running into maybe different from what you folks have. I figured out mine and it's more of a client configuration problem with HTTP calls to fastapi. I will draft up a PR and new issue specific for issue related to the one I ran into, and to be honest, it's more of a logging is not great when the request is aborted than anything else. I also noticed that if a request is aborted it seems like the LLM still tries to run the request anyway? I could be wrong

**Comment by Penglikai** [comment] 2024-05-06 07:31
Running into the same problem, vllm will random abort some of requests even the batch number is relatively small, say 10. Anyone working on this?

**Comment by senbinyu** [comment] 2024-05-17 03:48
Same problem, but I encountered it when the prompts are long(>16000 tokens) and the concurrent request number is relatively small, like 4. So what is the reason here, high workloads? Great thanks.

**Comment by yosefmih** [comment] 2024-06-17 18:19
I got this in two different scenarios. It happened when load testing my setup with a 1000 concurrent requests. A bunch of requests got aborted after the first couple of hundreds. Another setup I saw this in is while running a keda http scaler addon proxy in front of a k8s service I had created for my vllm pods. In the second case, as much as a single request causes abortion. I am not sure if I have something wrong with my http setup, but thought it might be worth sharing.

**Comment by ipackhu** [comment] 2024-06-18 00:56
I also got same problem. 
INFO 06-17 13:55:14 async_llm_engine.py:553] Received request 01c85dab24d84f6c8a8d6e57a3bc2c67: prompt: '<|begin_of_text|><|start_header_id|>
INFO 06-17 13:56:14 async_llm_engine.py:158] Aborted request 01c85dab24d84f6c8a8d6e57a3bc2c67.

Does it limit in 1 minute

**Comment by MBhartiya** [comment] 2024-06-26 06:28
@erjieyong I am facing the same issue, with nginx its failing with the same error, however without nginx, its working fine. Did you find any solution?

**Comment by ayrnb** [comment] 2024-07-23 13:37
+1

**Comment by carljones3000** [comment] 2024-07-27 23:00
+1 because I also get this for longer prompts. Confirmed that there's no error if the prompt it just a few words. Confirmed that this error occurs if prompt is about 500 words. Useing Qwen2 72B instruct on 8X3090.

```python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen2-72B-Instruct --tensor-parallel-size 8 --max-model-len 12591 --swap 1```

**Comment by carljones3000** [comment] 2024-07-28 01:13
> +1 because I also get this for longer prompts. Confirmed that there's no error if the prompt it just a few words. Confirmed that this error occurs if prompt is about 500 words. Useing Qwen2 72B instruct on 8X3090.
> 
> `python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen2-72B-Instruct --tensor-parallel-size 8 --max-model-len 12591 --swap 1`

Found the problem for my issue: the request time out was too short

**Comment by ayrnb** [comment] 2024-07-29 06:30
set  timeout larger will solve 
![image](https://github.com/user-attachments/assets/9977ba5e-e598-451c-8b4d-96f6b07725fb)

**Comment by coderchem** [comment] 2024-08-13 08:35
no，timout=1  not solve.

**Comment by 46319943** [comment] 2024-08-19 05:51
I am experiencing a similar issue. When the prompt is short, the response is returned normally. However, if the prompt is relatively long, the server logs the following error: `INFO 08-19 11:15:47 async_llm_engine.py:181] Aborted request chat-12fa08eea52d4308ab46efbdeb7a300a.`, and the client displays `Error: read ECONNRESET`.

@carljones3000, have you found a solution to this problem? Is there a way to adjust the request timeout?

In my tests using Postman, where the timeout is disabled, the request still fails. This suggests that the timeout issue may be occurring on the server side.

**Comment by 46319943** [comment] 2024-08-19 06:02
After some attempts, I found a temporary solution to the issue caused by the timeout. You can use the **stream** method by setting `"stream": true`. This allows the server to return the result continuously, preventing the request from being aborted.

For more information on using **stream**, refer to [this example](https://github.com/vllm-project/vllm/blob/main/examples/openai_completion_client.py).

**Comment by rocke2020** [comment] 2024-08-23 07:56
> After some attempts, I found a temporary solution to the issue caused by the timeout. You can use the **stream** method by setting `"stream": true`. This allows the server to return the result continuously, preventing the request from being aborted.
> 
> For more information on using **stream**, refer to [this example](https://github.com/vllm-project/vllm/blob/main/examples/openai_completion_client.py).

We use "stream": true, still with this problem

**Comment by TangJiakai** [comment] 2024-09-05 09:52
Still Error in 0.5.5, 0.6.0!!!!!!!!

**Comment by cicicji** [comment] 2024-09-10 03:49
Still Error in 0.6.0

**Comment by kjain14** [comment] 2024-09-10 16:40
Also getting this error

**Comment by rocke2020** [comment] 2024-09-19 03:03
> Also getting this error

could you report your version?

**Comment by kjain14** [comment] 2024-09-19 05:36
Version is 0.6.0, lowering my parallelism and deploying on more GPUs fixed things for me.

**Comment by naturomics** [comment] 2024-09-28 02:04
Same error, version 0.5.1

**Comment by nikhil05k** [comment] 2024-10-02 14:28
Still seeing this issue on 0.6.2. Works on some prompts when "stream": true

Works fine for very small prompts. But anything else, we see the "aborted request" INFO log. 

GPU: 2xV100 Tesla

Command used to start the server 
```
VLLM_LOGGING_LEVEL=DEBUG CUDA_LAUNCH_BLOCKING=1 VLLM_TRACE_FUNCTION=1 NCCL_DEBUG=TRACE NCCL_SHM_DISABLE=1 DISKCACHE_DIRECTORY=/data/ VLLM_CONFIG_ROOT=/data/ VLLM_CACHE_ROOT=/data/ XDG_CACHE_HOME=/data/ XDG_CONFIG_HOME=/data/ NUMBA_CACHE_DIR=/data/ OUTLINES_CACHE_DIR=/data/.outlines HF_HOME=/data/ TRANSFORMERS_CACHE=/data/ python3 -m vllm.entrypoints.openai.api_server --model mistralai/Mistral-Nemo-Instruct-2407 --dtype=half --tensor-parallel-size 2 --max-model-len 1024 --enforce-eager --ssl-certfile $tls_cert --ssl-keyfile $tls_key --port 8080 --download-dir /data/ --trust-remote-code
```

Model - mistralai/Mistral-Nemo-Instruct-2407

**Comment by stadlerb** [comment] 2024-10-09 14:13
We had a similar problem with long-running requests. In our case, it appears that each request is aborted almost exactly 5 minutes after it was added, e.g.:
```
...
INFO 10-09 11:52:56 async_llm_engine.py:208] Added request cmpl-e2fc958c1054455d9b2b6f8ce440a384-0.
...
INFO 10-09 11:57:57 async_llm_engine.py:220] Aborted request cmpl-e2fc958c1054455d9b2b6f8ce440a384-0.
...
```
(using the vLLM 0.5.5. Docker image)

This happens to coincide with the default torch distributed timeout, but explicitly specifying a timeout in init_process_group in vllm/distributed/parallel_state.py didn't help.

**Comment by erickrf** [comment] 2024-10-14 12:10
I'm having this problem even with a single request and a short prompt that ends up generating something above 500 tokens.

**Comment by njhill** [comment] 2024-10-15 20:50
This is most likely a client-side timeout, or some proxy between your client and vLLM that has a connection timeout. The request will be cancelled with this message printed in the logs when the caller closes the connection. It happens for larger number of tokens because those are the requests that take longer.

**Comment by erickrf** [comment] 2024-10-17 08:37
> This is most likely a client-side timeout, or some proxy between your client and vLLM that has a connection timeout. The request will be cancelled with this message printed in the logs when the caller closes the connection. It happens for larger number of tokens because those are the requests that take longer.

After further investigation, I can confirm that was the issue in my case. We were running vLLM (under kserve) in one kubernetes cluster and accessing it through LiteLLM, which ran on another cluster, and there was a policy to cap connections across clusters to 30 seconds. Thanks for answering!

**Comment by njhill** [comment] 2024-10-17 22:09
Closing this since it appears to have been resolved / due to external causes.

**Closed by njhill** 2024-10-17 22:09 UTC

**Comment by stadlerb** [comment] 2024-10-29 14:48
Even if it is an external cause, I'm not sure this should be closed, as the messages logged are unclear.
Would it be hard to somehow indicate in the log message that the request was aborted because the connection was closed and not due to some internal error in vLLM?

**Comment by danktec** [comment] 2024-11-01 05:33
For me, with an ALB, i changed the following and one of these things fixed it:
* Turn off HTTP/2
* connection idle timeout increase
* HTTP client keepalive duration increase
* Desync mitigation mode: monitor
* X-Forwarded-For header: preserve

One of these settings made out 504's go away. Perhaps someone can tell us which one 🦙

**Comment by sinpy1117** [comment] 2024-12-29 14:48
I encountered the same issue while deploying the qwen2vl-72b model using vLLM(0.6.4.post1). During the testing phase, I found that:

- When accessing directly via IP + Port, everything works fine.

- However, after configuring Nginx domain name proxy,  requests sometimes abort (without any apparent reason) and sometimes output normally

This issue only occurs when stream is set to true. When stream is set to false, everything works normally. I’ve gone through the previous Q&A above, but unfortunately, I couldn’t find a suitable solution.

<img width="1045" alt="image" src="https://github.com/user-attachments/assets/91c6dea8-8efd-4288-9c2c-867533c33cc2" />

**Comment by Yuhui0620** [comment] 2025-01-07 07:56
Same. Besides, It is hard to know what happened because the log message does not report in detail with some traces.

**Comment by Kevinstone-199898** [comment] 2025-02-26 15:42
It seems that the client closes the connection after 10 mins if it doesn't recieve a response by default. There is a parameter called "timeout" in Completions class, setting the parameter as a large number such as 100000000 can solve the problem.(I guess it represents the maximum number of seconds to close the connection)

<img width="767" alt="Image" src="https://github.com/user-attachments/assets/216b85b1-2b7b-4d6f-9b26-85c8d9c0a06b" />

<img width="1152" alt="Image" src="https://github.com/user-attachments/assets/4df4c1e1-e6ee-4320-b461-891fa7ce1e0c" />
