### ISSUE TITLE
inference Bug

### ISSUE THREAD

**Issue by yubuyuabc** [vllm-project/vllm#1130] opened 2023-09-21 12:22 UTC
问题描述：
使用vllm进行gpt2推理，输入prompt为空会触发以下error，之后任何请求都不会出结果，除非重启服务；不仅是这个场景，其他情况下触发这个error也会出现相同情况

Problem Description:
When using vllm for gpt2 inference, if the input prompt is empty, it triggers the following error, and thereafter no request will yield results unless the service is restarted. This situation occurs not only in this scenario but also in other cases where this error is triggered.

error:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/responses.py", line 273, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/responses.py", line 269, in wrap
    await func()
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/starlette/responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
  File "/data/lss/data_bak/KBQA/LLM/vllm/vllm/vllm/entrypoints/api_server.py", line 37, in stream_results
    async for request_output in results_generator:
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 148, in generate
    await self.engine_step(request_id)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 74, in engine_step
    request_outputs = self.engine.step()
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 454, in step
    self._decode_sequences(seq_groups)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 563, in _decode_sequences
    new_token, new_output_text = detokenize_incrementally(
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/vllm/transformers_utils/tokenizer.py", line 105, in detokenize_incrementally
    output_text = tokenizer.convert_tokens_to_string(output_tokens)
  File "/home/ubuntu/anaconda3/envs/lyra/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 533, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

**Comment by viktor-ferenczi** [comment] 2023-09-23 04:48
This issues does not seem to depend on the specific model, but depends only on the empty request.

What would be the best answer in the case of an empty prompt? I guess it should just fail the request with a `400 Bad Request` response and should not even reach the LLM.

**Comment by viktor-ferenczi** [comment] 2023-09-23 06:11
I could not reproduce this with HF model `gpt2` and an empty string `""` prompt.

Indeed, there is a crash if the prompt is `None` (`null`).

There is a similar cache if an unknown parameter is passed.

**Comment by viktor-ferenczi** [comment] 2023-09-23 06:14
Fixed in #1158

**Comment by hmellor** [comment] 2024-03-08 12:22
Closing as resolved

**Closed by hmellor** 2024-03-08 12:22 UTC
