### ISSUE TITLE
Feasible to implement  non-autoregressive LMs? (M2M)

### ISSUE THREAD

**Issue by Axreub** [vllm-project/vllm#1072] opened 2023-09-17 15:40 UTC
Hey. I'm starting to try to implement M2M in vLLM and noticed that all the currently supported models use Causal language models (decoder only), while M2M is non-autoregressive and has an encoder-decoder architecture. Is it still possible to implement a vLLM version of M2M or should I just give up 🥲 Appreciate any help with this : )

**Comment by irasin** [comment] 2023-09-18 10:10
Hi, @Axreub, I just wonder what is the non-autoregressive LMs(M2M), can you share the paper or code about it? Thanks a lot.

**Comment by Axreub** [comment] 2023-09-18 10:38
I mean specifically M2M-100, the translation model by Meta AI.[arXiv paper](https://arxiv.org/abs/2010.11125) [418M params model card on HF](https://huggingface.co/facebook/m2m100_418M)  [1.2B params model card on HF](https://huggingface.co/facebook/m2m100_1.2B). Sorry for not being clear enough previously. I'm mostly concerned about the fact that non-autoregressive models include a decoder with separate attention etc so I'm wondering if it's still feasible.

**Comment by hmellor** [comment] 2024-03-08 12:06
Closing as duplicate of #187

**Closed by hmellor** 2024-03-08 12:06 UTC
Labels: duplicate
