### ISSUE TITLE
The inference results based on vllm qwen7B also lead to a decrease in accuracy

### ISSUE THREAD

**Issue by lenten0000** [vllm-project/vllm#2953] opened 2024-02-21 10:06 UTC
Mainly due to significant differences from the original qwen7B answer, we hope to resolve this issue

**Comment by zhochengbiao** [comment] 2024-02-21 10:07
Yes, I also encountered this problem

**Comment by hmellor** [comment] 2024-08-27 10:11
Closing as duplicate of #2950

**Closed by hmellor** 2024-08-27 10:11 UTC
