### ISSUE TITLE
Add Support for Quantized Model in VLLM - $500 Reward

### ISSUE THREAD

**Issue by petrasS3** [vllm-project/vllm#744] opened 2023-08-12 08:52 UTC
We need to add support for the quantized model in the VLLM project. We need this to run a llama quantized model via vllm.  This involves implementing quantization techniques to optimize memory usage and runtime performance. A reward of $500 will be granted to the contributor who successfully completes this task.

**Comment by PadLex** [comment] 2023-08-12 10:29
Might be worth mentioning the 500$ reward in this issue #392

**Comment by petrasS3** [comment] 2023-08-15 21:41
> @petrasS3 There is fast implementation with merge request #762. Would this qualify? Just working on some cosmetic code-style improvements then it will be mergable.

omg this is amazing, did you test out TheBloke models and especially the GPTQ ones

**Comment by ri938** [comment] 2023-08-16 08:45
i tried to implement using GPTQ but AWQ quantization was faster and better inference quality.  

https://github.com/mit-han-lab/llm-awq/blob/main/scripts/llama_example.sh
here is a link to example of quantizing using AWQ, its very straightforward

**Comment by petrasS3** [comment] 2023-08-16 09:40
Does this mean GPTQ models cannot be loaded with this? Yes, AWQ is faster, but there are not that many models for it.

**Comment by viktor-ferenczi** [comment] 2023-08-16 22:54
Just having "load in 8-bit" support alone would be fine as a first step.

**Comment by petrasS3** [comment] 2023-08-16 23:16
> 

Did you try it with GPTQ?

**Comment by lvhan028** [comment] 2023-08-17 08:30
Aha, I recommend our project [LMDeploy](https://github.com/InternLM/lmdeploy), which support 4-bit weight  and 8-bit k/v cache quantization and inference.
Check the performance on Geforce RTX 4090 out. Totally worth 500$ :smile: 

| model            | llm-awq | mlc-llm | lmdeploy |
| ---------------- | ------- | ------- | --------- |
| Llama-2-7B-chat  | 112.9   | 159.4   | 206.4     |
| Llama-2-13B-chat | N/A     | 90.7    | 115.8     |

Memory (GB) comparison results between 4-bit and 16-bit model with context size 2048 and 4096 respectively,

| model            | 16bit(2048) | 4bit(2048) | 16bit(4096) | 4bit(4096) |
| ---------------- | ----------- | ---------- | ----------- | ---------- |
| Llama-2-7B-chat  | 15.1        | 6.3        | 16.2        | 7.5        |
| Llama-2-13B-chat | OOM         | 10.3       | OOM         | 12.0       |

**Comment by TheBloke** [comment] 2023-08-17 17:38
> Does this mean GPTQ models cannot be loaded with this? Yes, AWQ is faster, but there are not that many models for it.

I will be starting to upload AWQ models to HF soon, hopefully in the next few days.

**Comment by casperbh96** [comment] 2023-08-17 20:39
Working with AWQ models will also get easier soon enough when [#72](https://github.com/mit-han-lab/llm-awq/pull/72) is merged in AWQ. The plan is to make it easier to use so we can improve it.

**Comment by petrasS3** [comment] 2023-08-17 21:30
> Aha, I recommend our project [LMDeploy](https://github.com/InternLM/lmdeploy), which support 4-bit weight and 8-bit k/v cache quantization and inference. Check the performance on Geforce RTX 4090 out. Totally worth 500$ 😄
> 
> model	llm-awq	mlc-llm	lmdeploy
> Llama-2-7B-chat	112.9	159.4	206.4
> Llama-2-13B-chat	N/A	90.7	115.8
> Memory (GB) comparison results between 4-bit and 16-bit model with context size 2048 and 4096 respectively,
> 
> model	16bit(2048)	4bit(2048)	16bit(4096)	4bit(4096)
> Llama-2-7B-chat	15.1	6.3	16.2	7.5
> Llama-2-13B-chat	OOM	10.3	OOM	12.0

Where can I find the docs ?

**Comment by petrasS3** [comment] 2023-08-17 21:33
> > Does this mean GPTQ models cannot be loaded with this? Yes, AWQ is faster, but there are not that many models for it.
> 
> I will be starting to upload AWQ models to HF soon, hopefully in the next few days.

Will you share the code for quantizing AWQ ?

**Comment by TheBloke** [comment] 2023-08-17 21:45
> > > Does this mean GPTQ models cannot be loaded with this? Yes, AWQ is faster, but there are not that many models for it.
> > 
> > 
> > I will be starting to upload AWQ models to HF soon, hopefully in the next few days.
> 
> Will you share the code for quantizing AWQ ?

I'm expecting to just use the code from the main AWQ repo - it's documented here: https://github.com/InternLM/lmdeploy

Looks easy enough!

**Comment by lvhan028** [comment] 2023-08-18 03:18
> > Aha, I recommend our project [LMDeploy](https://github.com/InternLM/lmdeploy), which support 4-bit weight and 8-bit k/v cache quantization and inference. Check the performance on Geforce RTX 4090 out. Totally worth 500$ 😄
> > model	llm-awq	mlc-llm	lmdeploy
> > Llama-2-7B-chat	112.9	159.4	206.4
> > Llama-2-13B-chat	N/A	90.7	115.8
> > Memory (GB) comparison results between 4-bit and 16-bit model with context size 2048 and 4096 respectively,
> > model	16bit(2048)	4bit(2048)	16bit(4096)	4bit(4096)
> > Llama-2-7B-chat	15.1	6.3	16.2	7.5
> > Llama-2-13B-chat	OOM	10.3	OOM	12.0
> 
> Where can I find the docs ?

https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md

**Comment by petrasS3** [comment] 2023-08-18 04:10
> > > Aha, I recommend our project [LMDeploy](https://github.com/InternLM/lmdeploy), which support 4-bit weight and 8-bit k/v cache quantization and inference. Check the performance on Geforce RTX 4090 out. Totally worth 500$ 😄
> > > model	llm-awq	mlc-llm	lmdeploy
> > > Llama-2-7B-chat	112.9	159.4	206.4
> > > Llama-2-13B-chat	N/A	90.7	115.8
> > > Memory (GB) comparison results between 4-bit and 16-bit model with context size 2048 and 4096 respectively,
> > > model	16bit(2048)	4bit(2048)	16bit(4096)	4bit(4096)
> > > Llama-2-7B-chat	15.1	6.3	16.2	7.5
> > > Llama-2-13B-chat	OOM	10.3	OOM	12.0
> > 
> > 
> > Where can I find the docs ?
> 
> https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md

does it support the docker container because it keeps giving an error?

```txt
[ 96%] Built target triton-common-logging
[ 97%] Built target triton-common-thread-pool
[ 98%] Built target triton-common-table-printer
[ 99%] Linking CXX executable ../../../bin/llama_triton_example
/usr/bin/ld: CMakeFiles/llama_triton_example.dir/llama_triton_example.cc.o: in function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h:121: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: CMakeFiles/llama_triton_example.dir/llama_triton_example.cc.o: in function `MPI::Intracomm::Intracomm(ompi_communicator_t*)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h:23: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: CMakeFiles/llama_triton_example.dir/llama_triton_example.cc.o: in function `MPI::Intracomm::Intracomm()':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h:25: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h:25: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h:25: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h:25: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: CMakeFiles/llama_triton_example.dir/llama_triton_example.cc.o:/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h:25: more undefined references to `MPI::Comm::Comm()' follow
/usr/bin/ld: CMakeFiles/llama_triton_example.dir/llama_triton_example.cc.o:(.data.rel.ro._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: CMakeFiles/llama_triton_example.dir/llama_triton_example.cc.o:(.data.rel.ro._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `MPI::Win::Free()'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/cpp/llama/CMakeFiles/llama_triton_example.dir/build.make:132: bin/llama_triton_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:3040: examples/cpp/llama/CMakeFiles/llama_triton_example.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by lvhan028** [comment] 2023-08-18 05:05
> 

It supports docker. Can you open an issue in lmdeploy and tell us how to reproduce it?

**Comment by casperbh96** [comment] 2023-08-18 08:10
> Aha, I recommend our project [LMDeploy](https://github.com/InternLM/lmdeploy), which support 4-bit weight and 8-bit k/v cache quantization and inference. Check the performance on Geforce RTX 4090 out. Totally worth 500$ 😄
> 
> model	llm-awq	mlc-llm	lmdeploy
> Llama-2-7B-chat	112.9	159.4	206.4
> Llama-2-13B-chat	N/A	90.7	115.8
> Memory (GB) comparison results between 4-bit and 16-bit model with context size 2048 and 4096 respectively,
> 
> model	16bit(2048)	4bit(2048)	16bit(4096)	4bit(4096)
> Llama-2-7B-chat	15.1	6.3	16.2	7.5
> Llama-2-13B-chat	OOM	10.3	OOM	12.0

Are these numbers measured at batch size 1? Also, how to reproduce these numbers?

**Comment by faizanahemad** [comment] 2023-08-25 07:43
What's the progress here? Do we use [LMDeploy](https://github.com/InternLM/lmdeploy) or will vllm have support for this?

**Comment by TomExMachina** [comment] 2023-08-25 11:07
> What's the progress here? Do we use [LMDeploy](https://github.com/InternLM/lmdeploy) or will vllm have support for this?

It looks like #762 is close to being merged. I was sad to see "currently does not support tensor parallelism" but there is already [a fork](https://github.com/vllm-project/vllm/pull/762#issuecomment-1691224338) being worked on for that.

I only just learned of skypilot and started using it today. I think once that fork becomes a PR, AWQ quantized models can be deployed with skypilot as well?

**Comment by lvhan028** [comment] 2023-08-25 13:40
[LMDeploy](https://github.com/InternLM/lmdeploy) (>=v0.0.6) supports tensor parallelism for 4-bit quantized LLM model inference

**Comment by casper-hansen** [comment] 2023-08-25 13:46
> [LMDeploy](https://github.com/InternLM/lmdeploy) (>=v0.0.6) supports tensor parallelism for 4-bit quantized LLM model inference

What's the plan to support more models like MPT or Falcon?

**Comment by casper-hansen** [comment] 2023-08-30 18:56
> The only models I use are either Llama2-GPTQ or Flan-T5, so I can't use vLLM whatsoever. 😢

What do you mean by you can’t use it?

**Comment by casper-hansen** [comment] 2023-08-30 19:21
> > > The only models I use are either Llama2-GPTQ or Flan-T5, so I can't use vLLM whatsoever. 😢
> > 
> > 
> > What do you mean by you can’t use it?
> 
> vLLM doesn't support GPTQ models or T5 models, from what I can tell.

You should use AWQ models either way as they are better.

**Comment by casper-hansen** [comment] 2023-08-30 20:02
> 823 is greater than 47.
> <img alt="Screenshot 2023-08-30 at 12 54 21 PM" width="802" src="https://user-images.githubusercontent.com/286198/264458161-d8ef6540-3944-4951-9ed1-8b75d1b1a1d7.png">
> <img alt="Screenshot 2023-08-30 at 12 54 36 PM" width="801" src="https://user-images.githubusercontent.com/286198/264458174-c4f6e36c-ffda-4ec0-9de3-6e895efe15e1.png">

I already talked with TheBloke, more models will come for AWQ.

**Comment by PaulConyngham** [comment] 2023-09-03 00:05
does anyone know if VLLM support quantised models yet? Reading through these comments it looks like AWQ might be supported?

**Comment by faizanahemad** [comment] 2023-09-08 17:14
Is it possible to now directly use the AWQ models from HF Hub now?

**Comment by viktor-ferenczi** [comment] 2023-09-11 01:03
Does the AWQ support higher than 4 bits per weight? For example 8 bits like GGUF?

**Comment by casper-hansen** [comment] 2023-09-18 12:43
> Does AWQ support higher than 4 bits per weight? For example 8 bits like GGUF?

AWQ supports 4 bits per weight. Probably 8 bits will come at a later time.

**Comment by gleberof-ai** [comment] 2023-10-03 23:44
I tried the custom AWQ model with the latest vllm=0.2.0 - it allows to load a quantized model but without performance gain - I guess because it's dequantized during the load.
https://github.com/vllm-project/vllm/commit/2b1c116b5acdf3b738e310f98617875132214c37#diff-074bf1408c395d4d7dfaa07aaafaf6ebebb2b3bde50cdbbb868cc95d23daffb5

**Comment by hmellor** [comment] 2024-03-08 11:21
Closing as this is now resolved.

**Closed by hmellor** 2024-03-08 11:21 UTC

**Comment by manickavela29** [comment] 2024-07-26 12:11
so who won the $500 🙂
