### ISSUE TITLE
Failure to detect Ray installation

### ISSUE THREAD

**Issue by jconley-deloitte** [vllm-project/vllm#1147] opened 2023-09-22 14:53 UTC
![image](https://github.com/vllm-project/vllm/assets/116034543/fc48e90b-0135-4926-a85f-8ccdf4462200)
I've tried with different models, and there are 4 GPUs being made available.
Regardless of the model selected, it gives the same error claiming Ray is not installed, despite it clearly being installed/running

**Comment by viktor-ferenczi** [comment] 2023-09-23 04:02
Duplicate of #754

It has been fixed in https://github.com/vllm-project/vllm/commit/400b8289f744c4b8cdaa2c35268192c23e90d26c 

Until then the workaround is:
```sh
pip install --upgrade ray
pip install --upgrade pyarrow
pip install pandas
```

**Comment by WoosukKwon** [comment] 2023-09-28 02:28
Hi @jconley-deloitte, as @viktor-ferenczi answered above, we fixed this issue recently. Until a new release (which will be very soon), please additionally install pandas and pyarrow before using Ray.

**Closed by WoosukKwon** 2023-09-28 02:28 UTC
