### ISSUE TITLE
请问lora后的vl模型可以支持吗，如swift微调qwen-vl-chat后，可以支持部署吗

### ISSUE THREAD

**Issue by xs818818** [vllm-project/vllm#2902] opened 2024-02-17 15:13 UTC

**Comment by simon-mo** [comment] 2024-02-28 00:22
Does the LoRA support help solve your use case? [https://docs.vllm.ai/en/latest/models/lora.html](https://docs.vllm.ai/en/latest/models/lora.html)

**Comment by hmellor** [comment] 2024-08-27 09:44
Closing as duplicate of #962

**Closed by hmellor** 2024-08-27 09:44 UTC
