### ISSUE TITLE
[Misc]: Memory Order in Custom Allreduce

### ISSUE THREAD

**Issue by HydraQYH** [vllm-project/vllm#8404] opened 2024-09-12 08:23 UTC
# Memory Order in Custom Allreduce

In custom allreduce, i notice that `Signal*` has a `volatile` qualifier. And there are no memory fence in `start_sync` function. I want to know that can `volatile` will make right memory order? 
The `start_sync` program order is:
1. set start flag to other GPU's Signal
2. read start flag from local GPU's Signal
3. allreduce(pull data from other GPU)

In my opinion, without memory fence, the step 3 may be visible before Step 2 or 1.

**Comment by youkaichao** [comment] 2024-09-12 23:32
this is a great observation!

@kanghui0204 also fond this problem. it seems adding `__threadfence_system` can solve the problem, but at significant performance cost.

@HydraQYH do you have any ideas on how to solve it?

also cc @hanzhi713 if you still have bandwidth to investigate.

**Comment by hanzhi713** [comment] 2024-09-13 02:06
I don't think this is the issue. Step 3 will be executed after step 1 and 2 due to `__syncthreads()`, which is also a memory fence. During the execution of step 3, all GPUs should've at least entered the custom allreduce kernel (otherwise we'll be stuck at step 2), which means data is ready.

Even if step 3 got the wrong data, it won't cause a hang. If it hangs it must occur in one of the while loops.

**Comment by youkaichao** [comment] 2024-09-13 02:15
@hanzhi713 adding `__threadfence_system()`  in https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L137

seems to work, a solution found by @kanghui0204

I don't know if we can use some weaker sync op here, `__threadfence_system` might be too conservative.

**Comment by hanzhi713** [comment] 2024-09-13 02:24
@youkaichao Can you try what I proposed in the second bullet point of #8410?

I think the rationale behind this (I'm thinking about this too) is that the `end` reset https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L135 got reordered after https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L162

If this is indeed the case, it should be fixed by changing https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L156 to a unconditional fence.

**Comment by HydraQYH** [comment] 2024-09-13 02:31
> I don't think this is the issue. Step 3 will be executed after step 1 and 2 due to `__syncthreads()`, which is also a memory fence. During the execution of step 3, all GPUs should've at least entered the custom allreduce kernel (otherwise we'll be stuck at step 2), which means data is ready.
> 
> Even if step 3 got the wrong data, it won't cause a hang. If it hangs it must occur in one of the while loops.

@hanzhi713 Thanks for reply. I also think about the __syncthreads(). I'm not sure that if __syncthreads() has a memory fence semantic. In CUDA programming guide, it just say: 
`"__syncthreads() waits until all threads in the thread block have reached this point and all global and shared memory accesses made by these threads prior to __syncthreads() are visible to all threads in the block."`
So i make this issue.

**Comment by youkaichao** [comment] 2024-09-13 02:35
@hanzhi713  which will be more efficient?

adding `__threadfence_system` here:
https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L137

or 

unconditionally use `__threadfence_system` here:

https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L156

**Comment by hanzhi713** [comment] 2024-09-13 02:38
> > I don't think this is the issue. Step 3 will be executed after step 1 and 2 due to `__syncthreads()`, which is also a memory fence. During the execution of step 3, all GPUs should've at least entered the custom allreduce kernel (otherwise we'll be stuck at step 2), which means data is ready.
> > Even if step 3 got the wrong data, it won't cause a hang. If it hangs it must occur in one of the while loops.
> 
> @hanzhi713 Thanks for reply. I also think about the __syncthreads(). I'm not sure that if __syncthreads() has a memory fence semantic. In CUDA programming guide, it just say: `"__syncthreads() waits until all threads in the thread block have reached this point and all global and shared memory accesses made by these threads prior to __syncthreads() are visible to all threads in the block."` So i make this issue.

"... are visible to all threads in the block" this is a even stronger guarantee than a memory fence which only guarantees ordering.

**Comment by HydraQYH** [comment] 2024-09-13 02:38
> @hanzhi713 adding `__threadfence_system()` in
> 
> https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L137
> 
> seems to work, a solution found by @kanghui0204
> 
> I don't know if we can use some weaker sync op here, `__threadfence_system` might be too conservative.

@youkaichao I have tried this. In my A100, it will cause about 6us latency.

I tried to change the code to use weaker memory fence just like TensorRT-LLM. It seems that it will cause about 1~3us latency. It is better than `__threadfen_system()`. But still not good than @hanzhi713 's original implement without memory fence.

I can make a code review for my plan.

**Comment by hanzhi713** [comment] 2024-09-13 02:39
> @hanzhi713 which will be more efficient?
> 
> adding `__threadfence_system` here:
> 
> https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L137
> 
> or
> 
> unconditionally use `__threadfence_system` here:
> 
> https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L156

Second. It will add some latency to one stage allreduce, but two stage allreduce already has it, so overall impact is smaller.

**Comment by HydraQYH** [comment] 2024-09-13 03:05
> > @hanzhi713 adding `__threadfence_system()` in
> > https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L137
> > 
> > seems to work, a solution found by @kanghui0204
> > I don't know if we can use some weaker sync op here, `__threadfence_system` might be too conservative.
> 
> @youkaichao I have tried this. In my A100, it will cause about 6us latency.
> 
> I tried to change the code to use weaker memory fence just like TensorRT-LLM. It seems that it will cause about 1~3us latency. It is better than `__threadfen_system()`. But still not good than @hanzhi713 's original implement without memory fence.
> 
> I can make a code review for my plan.

TensorRT-LLM use both of fence(Acquire-Release) and __syncthreads: 
https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/customAllReduceKernels.cu#L172

@hanzhi713 
So maybe using both of them is more robust?

**Comment by kanghui0204** [comment] 2024-09-13 03:08
I saw @youkaichao 's comment , I think the problem is 
![problem](https://github.com/user-attachments/assets/ca7718cf-b81f-4e20-8112-edf2c183583b)

 I don't think switch end and start with 0/1 is a goodway , and I think the solution of below should be better , and don't need fence in one shot, how do you think?  @hanzhi713 @HydraQYH 

![solution](https://github.com/user-attachments/assets/82d940bb-4f65-4fcb-9c1b-4753c50e521f)

**Comment by hanzhi713** [comment] 2024-09-13 03:16
@kanghui0204 Your solution seems reasonable. It's worth a shot to see the performance.

**Comment by kanghui0204** [comment] 2024-09-13 03:19
OK, I'll try it sometime later

**Comment by HydraQYH** [comment] 2024-09-13 03:31
> I saw @youkaichao 's comment , I think the problem is ![problem](https://private-user-images.githubusercontent.com/20502162/367134923-ca7718cf-b81f-4e20-8112-edf2c183583b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg0MjMsIm5iZiI6MTcyNjE5ODEyMywicGF0aCI6Ii8yMDUwMjE2Mi8zNjcxMzQ5MjMtY2E3NzE4Y2YtYjgxZi00ZTIwLTgxMTItZWRmMmMxODM1ODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZmVhZjQ0NmU0ZGQ0MWRlNGU1Yzg3ODBlOTY1MjU2Njg5NTI4NGE0YTAzZjQxNTdmNjEzMjJlNGViNTZmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvCEqFw2f2Wudp2F5mViO7O9rKMfqfqmuZYD8I6spTk)
> 
> I don't think switch end and start with 0/1 is a good way , and I think the solution of below should be better , and don't need fence in one shot, how do you think? @hanzhi713 @HydraQYH
> 
> ![solution](https://private-user-images.githubusercontent.com/20502162/367135110-82d940bb-4f65-4fcb-9c1b-4753c50e521f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg0MjMsIm5iZiI6MTcyNjE5ODEyMywicGF0aCI6Ii8yMDUwMjE2Mi8zNjcxMzUxMTAtODJkOTQwYmItNGY2NS00ZmNiLTljMWItNDc1M2M1MGU1MjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZjAxMGIxZDEzYTE5ZWQ3OTc0YTY4MWNiNTAzZmY1N2M1Njk0ODY2OGY5MTU4NTI2NmNkNzk5MDQwNTA3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ty78dMEp5REwJ6qZY61eqnVGe1XUja-nkod3dkJ1paY)

Very interesting! I guess that in two-cards scenario, it seems really good. How about the 4-cards or 8 cards? I'm exciting to seen the performance result.

**Comment by kanghui0204** [comment] 2024-09-13 03:36
> > I saw @youkaichao 's comment , I think the problem is ![problem](https://private-user-images.githubusercontent.com/20502162/367134923-ca7718cf-b81f-4e20-8112-edf2c183583b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg0MjMsIm5iZiI6MTcyNjE5ODEyMywicGF0aCI6Ii8yMDUwMjE2Mi8zNjcxMzQ5MjMtY2E3NzE4Y2YtYjgxZi00ZTIwLTgxMTItZWRmMmMxODM1ODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZmVhZjQ0NmU0ZGQ0MWRlNGU1Yzg3ODBlOTY1MjU2Njg5NTI4NGE0YTAzZjQxNTdmNjEzMjJlNGViNTZmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvCEqFw2f2Wudp2F5mViO7O9rKMfqfqmuZYD8I6spTk)
> > I don't think switch end and start with 0/1 is a good way , and I think the solution of below should be better , and don't need fence in one shot, how do you think? @hanzhi713 @HydraQYH
> > ![solution](https://private-user-images.githubusercontent.com/20502162/367135110-82d940bb-4f65-4fcb-9c1b-4753c50e521f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTg0MjMsIm5iZiI6MTcyNjE5ODEyMywicGF0aCI6Ii8yMDUwMjE2Mi8zNjcxMzUxMTAtODJkOTQwYmItNGY2NS00ZmNiLTljMWItNDc1M2M1MGU1MjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAzMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZjAxMGIxZDEzYTE5ZWQ3OTc0YTY4MWNiNTAzZmY1N2M1Njk0ODY2OGY5MTU4NTI2NmNkNzk5MDQwNTA3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ty78dMEp5REwJ6qZY61eqnVGe1XUja-nkod3dkJ1paY)
> 
> Very interesting! I guess that in two-cards scenario, it seems really good. How about the 4-cards or 8 cards? I'm exciting to seen the performance result.

I think this works for all num of GPUs, because you can prepare a pair of flags for each other GPUs.

**Comment by youkaichao** [comment] 2024-09-13 04:56
@kanghui0204 I think you only need one local flag regardless of gpus, but global flags increase as the number of gpus?

every gpu has a flag array `bool flags[N]`, where `flags[i]` is gpu i's local flag, and the rest flags are global flags.
all the flags from all gpus form one array `bool all_flags[N][N]` (can be shared via p2p, or can be host managed memory mapped to device).

every gpu concurrently execute the following:

```c++

    const int N = 4; // Number of GPUs
    int i = 0; // GPU index

    // Assuming all_flags is an N x N 2D array
    int all_flags[N][N] = {0}; // Initialize all elements to 0, and this array is shared across all gpus

    // Update flags for the current GPU
    all_flags[i][i] += 1;

    // Update flags for peer GPUs
    for (int j = 0; j < N; ++j) {
        if (j != i) {
            all_flags[j][i] += 1;
        }
    }

    // Wait until synchronization is achieved
    bool synced = false;
    while (!synced) {
        synced = true;
        for (int j = 0; j < N; ++j) {
            if (all_flags[i][j] != all_flags[i][i]) {
                synced = false;
                break; // No need to check further, already out of sync
            }
        }
    }
```

the diagram:

<img width="911" alt="image" src="https://github.com/user-attachments/assets/26dc3458-ba05-48e7-97fd-9f4884a924da">

this essentially act as a barrier for all gpus.

**Comment by HydraQYH** [comment] 2024-09-13 08:37
> @hanzhi713 adding `__threadfence_system()` in
> 
> https://github.com/vllm-project/vllm/blob/0af3abe3d3225449c907d75eb3d2ae4b83bd21a1/csrc/custom_all_reduce.cuh#L137
> 
> seems to work, a solution found by @kanghui0204
> 
> I don't know if we can use some weaker sync op here, `__threadfence_system` might be too conservative.

cc@youkaichao https://github.com/vllm-project/vllm/issues/8410#issuecomment-2348359732

**Comment by HydraQYH** [comment] 2024-09-13 09:36
Move to https://github.com/vllm-project/vllm/issues/8457

**Comment by kanghui0204** [comment] 2024-09-14 00:54
> @kanghui0204 I think you only need one local flag regardless of gpus, but global flags increase as the number of gpus?
> 
> every gpu has a flag array `bool flags[N]`, where `flags[i]` is gpu i's local flag, and the rest flags are global flags. all the flags from all gpus form one array `bool all_flags[N][N]` (can be shared via p2p, or can be host managed memory mapped to device).
> 
> every gpu concurrently execute the following:
> 
> ```c++
>     const int N = 4; // Number of GPUs
>     int i = 0; // GPU index
> 
>     // Assuming all_flags is an N x N 2D array
>     int all_flags[N][N] = {0}; // Initialize all elements to 0, and this array is shared across all gpus
> 
>     // Update flags for the current GPU
>     all_flags[i][i] += 1;
> 
>     // Update flags for peer GPUs
>     for (int j = 0; j < N; ++j) {
>         if (j != i) {
>             all_flags[j][i] += 1;
>         }
>     }
> 
>     // Wait until synchronization is achieved
>     bool synced = false;
>     while (!synced) {
>         synced = true;
>         for (int j = 0; j < N; ++j) {
>             if (all_flags[i][j] != all_flags[i][i]) {
>                 synced = false;
>                 break; // No need to check further, already out of sync
>             }
>         }
>     }
> ```
> 
> the diagram:
> 
> <img alt="image" width="911" src="https://private-user-images.githubusercontent.com/23236638/367157493-26dc3458-ba05-48e7-97fd-9f4884a924da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzU0NzcsIm5iZiI6MTcyNjI3NTE3NywicGF0aCI6Ii8yMzIzNjYzOC8zNjcxNTc0OTMtMjZkYzM0NTgtYmEwNS00OGU3LTk3ZmQtOWY0ODg0YTkyNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAwNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkODMxMzEzY2IyNzljMGZjNTBjMWM4OGFiM2U3NGE4MjhhNzUxOTVkMmNlMDNmMjc5MzkxYmZkNWU4YTg5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RZMGnKc6hhYo-kK6oU3VXOtEmO03TkVovKpSfNkuMik">
> this essentially act as a barrier for all gpus.

yes I agree with you.

**Comment by hanzhi713** [comment] 2024-09-17 07:08
@kanghui0204 I can take a stab at this idea if you haven't started. I happen to have some time this week.

**Comment by kanghui0204** [comment] 2024-09-17 08:52
> @kanghui0204 I can take a stab at this idea if you haven't started. I happen to have some time this week.

@hanzhi713 Sorry , I don't start it because Mid-autumn festival , if you have time  , you can have a try , thanks , and happy  Mid-autumn festival.

**Comment by hanzhi713** [comment] 2024-09-17 16:48
@kanghui0204  Sure. I will get started today. Happy holiday!

**Closed** 2024-09-24 09:21 UTC
Labels: misc
