### ISSUE TITLE
Qwen streaming inference leads to a significant decrease in accuracy

### ISSUE THREAD

**Issue by lishuai9584** [vllm-project/vllm#2954] opened 2024-02-21 10:13 UTC
The flow cytometry results of vllm for qwen7B or qwen14B are inconsistent with the original qwen results, resulting in an accuracy decrease of 10% -20%.

**Comment by hmellor** [comment] 2024-08-27 10:12
Closing as duplicate of #2950

**Closed by hmellor** 2024-08-27 10:12 UTC
