### ISSUE TITLE
Serving multiple models in vLLM with single or multiple engines

### ISSUE THREAD

**Issue by mevince** [vllm-project/vllm#3326] opened 2024-03-11 22:54 UTC
Is it possible to serve multiple models inside vLLM? It would be nice to choose which GPUs should load which model.
My guess is no since the rest of gpu memory is reserved for the single model's kv cache

**Comment by simon-mo** [comment] 2024-03-12 20:47
Duplicate of #299

**Closed by simon-mo** 2024-03-12 20:47 UTC
